### DISCUSSION TITLE
Able to push image to ECR with Kaniko but pull stuck on `ContainersNotReady containers with unready status: [polyaxon-main polyaxon-sidecar] `

### DISCUSSION THREAD

**Discussion by sathoune** [polyaxon/polyaxon#1294] [Q&A] [answered]
This question was resolved and discussed on Polyaxon Slack. Posting for visibility if someone stumbles upon the same issue.
### Given setup:
* Docker-registry provider: Amazon Elastic Container Registry (ECR)
* Polyaxon version: 1.7.3 CE
* Deployed with Kubernetes on AWS

### And built image at:
`ID.dkr.ecr.REGION.amazonaws.com/VALID-DIRECTORY/VALID-REPO:polyaxon-1`

### And polyaxonfile based on [xgboost/boston example](https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/xgboost/boston/polyaxonfile.yml) :
you can see that `run.environment` was added to expose `aws-secret` and `run.container.image` was substituted with above

```yaml

version: 1.1
kind: component
tags: [examples, xgboost]
inputs:
  - {name: max_depth, type: int, isOptional: true, value: 5}
  - {name: eta, type: float, isOptional: true, value: 0.5}
  - {name: gamma, type: float, isOptional: true, value: 0.1}
  - {name: subsample, type: int, isOptional: true, value: 1}
  - {name: lambda, type: int, isOptional: true, value: 1}
  - {name: alpha, type: float, isOptional: true, value: 0.35}
  - {name: objective, type: str, isOptional: true, value: 'reg:squarederror'}
  - {name: cross_validate, type: bool, isOptional: true, value: false}
run:
  kind: job
  connections: [docker-registry]
  environment:
    imagePullSecrets:
     - aws-secret
  init:
  - git: {"url": "https://github.com/polyaxon/polyaxon-examples"}
  container:
    image: ID.dkr.ecr.REGION.amazonaws.com/VALID-DIRECTORY/VALID-REPO:polyaxon-1
    workingDir: "{{ globals.artifacts_path }}/polyaxon-examples/in_cluster/xgboost/boston"
    command: ["python", "-u", "model.py"]
    args: [
      "--max_depth={{ max_depth }}",
      "--eta={{ eta }}",
      "--gamma={{ gamma }}",
      "--subsample={{ subsample }}",
      "--lambda={{ lambda }}",
      "--alpha={{ alpha }}",
      "--objective={{ objective }}",
      "--cross_validate={{ cross_validate }}",
    ]
```

### Then experiment would start but would be stuck on status indifinetely:
```
Conditions:
TYPE      STATUS    REASON                MESSAGE                                                           LAST_UPDATE_TIME    LAST_TRANSITION_TIME
--------  --------  --------------------  ----------------------------------------------------------------  ------------------  ----------------------
created   True      OperationServiceInit  Run is created                                                    a few seconds ago   a few seconds ago
compiled  True      SchedulerPrepare      Run is compiled                                                   a few seconds ago   a few seconds ago
queued    True      SchedulerStart        Run is queued                                                     a few seconds ago   a few seconds ago
starting  True      OperatorController    Operation is starting                                             a few seconds ago   a few seconds ago
warning   True      ContainersNotReady    containers with unready status: [polyaxon-main polyaxon-sidecar]  a few seconds ago   a few seconds ago
```

### And manually creating dummy pod with helm:
was also not able to be built due to error with pulling the image.
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: POLYAXON_NAMESPACE
spec:
  containers:
  - name: test
    image: ECR_IMAGE_TO_TEST
    command:
    - '/bin/bash'
    - '-c'
    args:
    - echo
    - "works"
```
