### DISCUSSION TITLE
(How) Can I pass path to Dockerfile using Kaniko?

### DISCUSSION THREAD

**Discussion by sathoune** [polyaxon/polyaxon#1315] [Q&A] [answered]
# Context
Let's say I have following structure
```
root
├──model_files
├──polyaxonfiles
│      ├──build.yml
│      └──run.yml
├──utils
└──dockerfiles
         ├──Dockerfile.0
         └──Dockerfile.1
```

my build looks as simple as:

```yaml
version: 1.1
kind: operation
name: build
params:
  context:
    value: "{{ globals.run_artifacts_path }}/uploads"
  destination:
    connection: docker-registry
    value: machine-learning/polyaxon-tutorial:1

hubRef: kaniko
```
Running this with command
```bash
polyaxon run -f polyaxonfiles/build.yml -u
```

Gives me very much expected error:
```bash
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

So the Kaniko expects `Dockerfile` to exist in root of the context by default. Does the polyaxonfile specification exposes a way to overwrite the default as suggested with error message?
