### DISCUSSION TITLE
Make references dynamic in DAGs

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1475] [Ideas]
> From slack

I would like to use a parameter with a ref to a run whose uuid is read from a parameter. For example, inside a DAG I can do the following:

```yaml
params:
  my_arg:
    value: artifacts.my_artifact
    ref: ops.my_op_in_the_same_dag
```

I would also like to do

```yaml
params:
  my_arg:
    value: artifacts.my_artifact
    ref: runs.{{ params.upstream_run_uuid_not_in_this_dag }}
```

This is not possible at the moment because params object isn't ready in this context. But I guess with some dependency resolution, it could be made to work? I have a workaround for this myself (I'm generating polyaxonfiles on the fly based on some input arguments, so I can inject the UUID at compile time to the polyaxonfile), but IMO such a feature would be useful.
