### DISCUSSION TITLE
How to use boolean params as string values without converting to a boolean values

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1477] [Q&A] [answered]
> From slack

I have a problem with plx CLI, a param of type `str` with value `False` that gets converted automatically, but I want to have a string parameter:

```yaml
- {name: add_noise,       type: str,   isOptional: true, value: "False"}
```

Polyaxon compiles the YAML to 

```yaml
inputs:
  - ...
  - name: add_noise
    type: str
    value: false  <-----
    isOptional: true

run:
  ...
  container:
    args:
      - ...
      - '--add_noise=false' <----
```
