### DISCUSSION TITLE
How can I start a Tensorboard for the top 5 experiments

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1483] [Q&A] [answered]
> From slack

I would like to compare the top 4 experiments based on a specific metrics.

Currently I query the top experiment using the cli:
```bash
polyaxon ops ls -q "name: GROUP_NAME, metrics.loss:<0.002"  -s "metrics.loss" -l 5
```

And then I copy/paste the run UUIDs to:

```bash
polyaxon run --hub tensorboard:mulit-run -P uuids=UUID1,UUID2,UUID3,UUID4,UUID5
```

**Comment by polyaxon-team** [comment, marked as answer]
From the UI or using a YAML file, you can run:

```yaml
version: 1.1
kind: operation
hubRef: tensorboard:multi-run
joins:
- query: "name: GROUP_NAME, metrics.loss:<0.002,  kind:job"  
  sort: "metrics.loss"
  limit: 5
  params:
    uuids: {value: "globals.uuid"}
```

Note that in the UI if create a filter / sort configuration, you can automatically create a multi-run Tensorboard based on that query, for example:

![Screenshot 2022-04-07 at 14 58 40](https://user-images.githubusercontent.com/24545041/162204216-a8d51984-7cd9-4992-8b3f-f31d617544db.png)

![Screenshot 2022-04-07 at 14 59 10](https://user-images.githubusercontent.com/24545041/162204329-d042f4d1-874c-426b-87c7-4ee47e83a721.png)
