### DISCUSSION TITLE
I would like to configure Polyaxon in a way to avoid asking data-scientists to configure pre-emptible node-pools or request TPUs on their own

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1484] [Q&A] [answered]
> From slack

I am currently defining some machines configuration using `machine-env1.yaml`, `machine-env2.yaml` which basically contains node selectors and CPU, GPU, and TPU requests configuration, and then running:

```bash
polyaxon run -f polyaxonfile.yaml -f machine-env1.yaml
```

I have two problems with this approach:
 1. I need to copy the env files to all our git repos, which means if I make a change I need to perform several pull requests
 2. I need to tell the data-scientits to pull the last commit, sometimes that's not possible because they can not merge/rebase the changes.

Based on those two issues, in the end we tell data-scientists to just use:

```yaml
environment:
  nodeSelector:
    nodes: large-pool
...
run:
  ...
  container:
      resources:
        limits:
          cpu: 3000m
          memory: 6000Mi
        requests:
          cpu: 2000m
          memory: 4000Mi
```
Which is error prone and confusing for them, and make the files bigger and difficult to change.

Any elegant way to abstract this type of configuration from the data-scientists?
