### DISCUSSION TITLE
How to patch a multi-run downstream operation, for example tensorboard:multi-run

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1502] [Q&A] [answered]
> From slack

Hi, simple Q. I want to launch a tensorboard with the tensorboard profiler pip installed from the GUI. At the moment I am using this:

```yaml
version: 1.1
kind: operation
hubRef: tensorboard:multi-run
joins:
- query: "uuid: XX"
  params:
    uuids: {value: "globals.uuid"}
```

However I want to runPatch it so that it installs:
```bash
pip install -U tensorboard-plugin-profile
```

Is there a way to easily do this?

**Comment by polyaxon-team** [comment, marked as answer]
You can add the following `runPatch`:

```yaml
...
patchStrategy: replace
runPatch:
  container:
    command: ["bash", "-c"]
    args:
      - "pip install -U tensorboard-plugin-profile && tensorboard --logdir={{globals.artifacts_path}} --port={{globals.ports[0]}} --path_prefix={{globals.base_url}} --host=0.0.0.0"
```

For the specific case of tensorboard, we will add a new input `plugins` of type `List[str]` to the [tensorboard component versions ](https://cloud.polyaxon.com/ui/polyaxon/tensorboard/) , so instead of patching the component, users can pass a parameter:

```yaml
params:
  plugins: { value: [tensorboard-plugin-profile, tensorboard-plugin-custom, ...] }
```
