### DISCUSSION TITLE
How to start a tensorboard for all runs that are part of a hyperparameter tuning operation

### DISCUSSION THREAD

**Discussion by polyaxon-team** [polyaxon/polyaxon#1503] [Q&A] [answered]
> From slack

Currently, I am selecting all runs from the table and then creating a multi-run downstream operation. with the id of those runs.
Ideally, there should be a simple way to start such multi-run tensorboard without manually selecting the runs, especially when the number of run of the hyperparameter operation is very large, at least larger than the maximum number of runs allowed by the pagination:  50.

**Comment by polyaxon-team** [comment, marked as answer]
You do not have to manually select the runs for a hyperparameter operation, you can use the pipeline operation's uuid to query all, or a subset, runs belonging to that matrix operation:

```yaml
version: 1.1
kind: operation
hubRef: tensorboard:multi-runs
joins:
- query: "pipeline: MATRIX_UUID"
  params:
    uuids: {value: "globals.uuid"}
```

To filter further by a specific condition, for example loss metric:

```yaml
version: 1.1
kind: operation
hubRef: tensorboard:multi-runs
joins:
- query: "pipeline: MATRIX_UUID, metrics.loss: < 0.02"
  sort: metrics.loss
  limit: 60
  params:
    uuids: {value: "globals.uuid"}
```
