### DISCUSSION TITLE
Can I add Component Tags via Input Params?

### DISCUSSION THREAD

**Discussion by AffineParameter** [polyaxon/polyaxon#1518] [Q&A]
I have no idea if this is possible, but I found myself wanting to do the following.

In words, I want to add component tags based on matrix parameters. The following `yaml` doesn't work, but I think it illustrates what I want.

```yaml
version: 1.1
kind: operation
matrix:
  kind: grid
  params:
    sota:
      kind: choice
      value:
        - model: ModelA
          max_epochs: 200
          dataset_hash: ae43ff
        - model: ModelB
          max_epochs: 150
          dataset_hash: 33fba2
component:
  name: model-trainer
  tags:
    - dataset_update_retrain
    - "{{ sota.model }}"  #<- I want to set this dynamically based on the job input
  inputs:
    - name: sota
      type: dict
      isOptional: false
  run:
    kind: job
    container:
      args: >
        set -x;
       train \
          hydra.run.dir={{ globals.run_outputs_path }} \
          model={{ sota.model }} \
            model.datamodule.dataset_hash={{ sota.dataset_hash }}/ \
            model.datamodule.data_directory=/data/{{ sota.model }}/ \
          trainer=gpu \
            trainer.max_epochs={{ sota.max_epochs }} \
      ...
```

As the above pattern doesn't work, I am either doing it wrong or it isn't possible in the config. Could I potentially set ENV vars that could get picked up by the tracking client?

Thanks a ton for the help!
