### ISSUE TITLE
Issues with polyaxon chart: artifactsStore as a table

### ISSUE THREAD

**Issue by boniek83** [polyaxon/polyaxon#1031]
### Describe the bug
Helm expects artifactsStore to be a table:
`coalesce.go:160: warning: skipped value for artifactsStore: Not a table.`
but documentation has no mention of this (I'm under impression you can only have one entry under artifactStore). Default value of artifactsStore is not table in values.yaml
When converted artifactsStore entry to table entry like so:
```
artifactsStore:
  -  name: artifactstore
     kind: volume_claim
     schema: 
       mountPath: /artifactstore
       volumeClaim: polyaxon-default-artifactstore
```
helm complains:
`Error: UPGRADE FAILED: template: polyaxon/templates/streams-deployment.yaml:41:3: executing "polyaxon/templates/streams-deployment.yaml" at <include "config.artifactsStore.envFrom" .>: error calling include: template: polyaxon/templates/partials/_stores.tpl:6:14: executing "config.artifactsStore.envFrom" at <.Values.artifactsStore.secret>: can't evaluate field secret in type interface {}`
I don't need a secret with volume_claim.
### To Reproduce
Normal helm install/upgrade.

### Environment
Helm 3.3.0
Polyaxon 1.1.7

**Comment by mouradmourafiq** [comment]
Yes one entry:

```yaml
artifactsStore:
  name: artifactstore
   kind: volume_claim
   schema: 
     mountPath: /artifactstore
     volumeClaim: polyaxon-default-artifactstore
```
