### ISSUE TITLE
How to run pods based on different images in two workers when supporting tfjob

### ISSUE THREAD

**Issue by zhaohb** [polyaxon/polyaxon#1043]
Now I want to run a distributed tensorflow training task, I want to start two workers and a ps, and the images of the two workers are different, but the tasks are the same, how should I write the yaml file

``` yaml
version: 1.1
kind: component
name: cpu-tfjob
run:
  kind: tfjob
  worker:
    replicas: 2
    container:
      name: cpu-tfjob-worker1
      image: polyaxon-tf:1.5.0-devel-cpu-py36-polyaxon
      command: ["python", "/tensorflow_distributed_example/mnist_tf_dist.py"]

##maybe the another worker config like that:
    container:
      name: cpu-tfjob-worker2
      image: nginx:v1
      command: ["python", "/tensorflow_distributed_example/mnist_tf_dist.py"]

  ps:
    replicas: 1
    container:
      name: cpu-tfjob-ps1
      image: polyaxon-tf:1.5.0-devel-cpu-py36-polyaxon
      command: ["python", "/tensorflow_distributed_example/mnist_tf_dist.py"]

```

thank you very much
