### ISSUE TITLE
Tensorboard stops to update after a while

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#1047]
### Describe the bug
When running an experiment and starting a Tensorboard service, it updates the metrics and dashboard properly in the beginning, but it stops to update after a minute or so. We are running minIO as our artifactsStore.
### To Reproduce
```
version: 1.1
kind: component
name: simple-experiment
description: Minimum information to run this TF.Keras example
tags: [examples]
run:
  kind: job
  init:
  - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
    container:
      env:
        - name: http_proxy
          value: "***"
        - name: https_proxy
          value: "***"
  container:
    image: polyaxon/polyaxon-quick-start
    workingDir: "{{ globals.artifacts_path }}/polyaxon-quick-start"
    command: [python3, model.py]
    env:
      - name: http_proxy
        value: "***"
      - name: https_proxy
        value: "***"
```
`polyaxon run --hub tensorboard -P uuid=<uuid>`

### Expected behavior
Continuous update of Tensorboard metrics.

### Environment
```
deploymentChart: platform
deploymentVersion: 1.1.3

artifactsStore:
  name: minio
  kind: s3
  schema: {"bucket": "***"}
  secret:
    name: "***"

connections:
  - name: data
    kind: volume_claim
    schema:
      mountPath: ***
      volumeClaim: ***
      readOnly: true

scheduler:
  enabled: true

streams:
  enabled: true

postgresql:
  persistence:
    enabled: true
    storageClass: nfs

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: nfs
  slave:
    persistence:
      enabled: true
      storageClass: nfs
broker: redis

rabbitmq-ha:
  enabled: false

adminViewEnabled: true
```
