### ISSUE TITLE
Can't checkout github repo with ssh

### ISSUE THREAD

**Issue by swimablefish** [polyaxon/polyaxon#1063]
### Describe the bug

I tried to checkout the repo with ssh, but fail, the error message is :

File \"\/usr\/local\/lib\/python3.8\/site-packages\/polyaxon\/init\/git.py\", line 47, in get_clone_url"

Based on the code https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/init/git.py#L47, it will fail if the url doesn't start with `https://`

### To Reproduce

```yaml
version: 1.1
kind: component
name: simple-experiment3
description: Minimum information to run this TF.Keras example
tags: ["test"]
run:
  kind: job
  init:
  - git: {url: "git@github.com:xxx/xxxx.git"}
  container:
    image: busybox
    workingDir: "{{ globals.artifacts_path }}/path"
    command: [sleep, 120s]
```
### Expected behavior
it can checkout the github repo with ssh, like `git@github.com:polyaxon/polyaxon.git`
