### ISSUE TITLE
Deleting a job/service doesn't stop it and can't be stopped afterwards

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#1068]
### Describe the bug
When deleting a job from the UI, it gets removed from the UI, however it doesn't stop the pod running, and I can't stop the job afterwards since it has been removed from the UI, and just deleting the pod/deployment just restarts it.
Stopping it from the CLI also doesn't work:
```
polyaxon ops --uid=fe25ef596b4f4fd093f35447880e70cf stop
Are sure you want to stop run `fe25ef596b4f4fd093f35447880e70cf` [y/N]: y
Could not stop run `fe25ef596b4f4fd093f35447880e70cf`.
Status: 404. The resource you are looking for was not found. Check if the name or uuid is correct.
```

This also affects services such as Tensorboard.
### To Reproduce
```
polyaxon version

Current cli version: 1.1.8.
```
```
version: 1.1
kind: component
name: simple-experiment
description: Minimum information to run this TF.Keras example
tags: [examples]
run:
  kind: job
  init:
  - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
    container:
      env:
        - name: http_proxy
          value: "***"
        - name: https_proxy
          value: "***"
  container:
    image: polyaxon/polyaxon-quick-start
    workingDir: "{{ globals.artifacts_path }}/polyaxon-quick-start"
    command: ["python3", "model.py", "--epochs", "30"]
    env:
      - name: http_proxy
        value: "***"
      - name: https_proxy
        value: "***"
```
Then navigate to the created job in the UI, wait for it to start, and then delete it.

### Expected behavior
The job should stop and be fully removed.

### Environment
```
deploymentChart: platform
deploymentVersion: 1.1.8

artifactsStore:
  name: minio
  kind: s3
  schema: {"bucket": "***"}
  secret:
    name: "***"

connections:
  - name: data
    kind: volume_claim
    schema:
      mountPath: ***
      volumeClaim: ***
      readOnly: true

scheduler:
  enabled: true

streams:
  enabled: true

postgresql:
  persistence:
    enabled: true
    storageClass: nfs

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: nfs
  slave:
    persistence:
      enabled: true
      storageClass: nfs
broker: redis

rabbitmq-ha:
  enabled: false

ui:
  enabled: true
  adminEnabled: true
```
