### ISSUE TITLE
Deleting a job doesn't delete it's artifacts on artifactsStore (minIO)

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#1072]
### Describe the bug
When deleting a job from the UI, it gets removed from the UI, however it doesn't clean the artifacts from the artifactsStore. Previous versions of Polyaxon did this (0.6).

### To Reproduce
```
polyaxon version

Current cli version: 1.1.8.
```
```
version: 1.1
kind: component
name: simple-experiment
description: Minimum information to run this TF.Keras example
tags: [examples]
run:
  kind: job
  init:
  - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
    container:
      env:
        - name: http_proxy
          value: "***"
        - name: https_proxy
          value: "***"
  container:
    image: polyaxon/polyaxon-quick-start
    workingDir: "{{ globals.artifacts_path }}/polyaxon-quick-start"
    command: ["python3", "model.py", "--epochs", "30"]
    env:
      - name: http_proxy
        value: "***"
      - name: https_proxy
        value: "***"
```
Then navigate to the created job in the UI, wait for it to finish, then delete it and check MinIO.

### Expected behavior
The job should be deleted and artifacts removed.

### Environment
```
deploymentChart: platform
deploymentVersion: 1.1.8

artifactsStore:
  name: minio
  kind: s3
  schema: {"bucket": "***"}
  secret:
    name: "***"

connections:
  - name: data
    kind: volume_claim
    schema:
      mountPath: ***
      volumeClaim: ***
      readOnly: true

scheduler:
  enabled: true

streams:
  enabled: true

postgresql:
  persistence:
    enabled: true
    storageClass: nfs

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: nfs
  slave:
    persistence:
      enabled: true
      storageClass: nfs
broker: redis

rabbitmq-ha:
  enabled: false

ui:
  enabled: true
  adminEnabled: true
```
