### ISSUE TITLE
Improve connection dependent types

### ISSUE THREAD

**Issue by polyaxon-team** [polyaxon/polyaxon#1074]
### Current behavior

Some types are confusion and have some implicit errors. For instance:

```yaml
init:
  - git: {url: "https://github.com/test/repo", connection: "git-connection"}
  - artifacts: {files: "some-files", connection: "s3-connection"}
```
This will not raise an error because the same type is also expected to work as a param, however the compiler discard this field and expect a connection on the same level as the type when used in the `init` section, correct behavior:

 
```yaml
init:
  - git: {url: "https://github.com/test/repo"}
    connection: "git-connection"
  - artifacts: {files: "some-files"}
    connection: "s3-connection"
```

### Enhancement

We should remove the connection from the types, and similar to `search`, `ref`, and `value` we should add `connection` and a flag `init` to enable turning params to an init entry.
