### ISSUE TITLE
Log image with path causes 404 in dashboard

### ISSUE THREAD

**Issue by gmrukwa** [polyaxon/polyaxon#1112]
### Describe the bug

I was marking pngs produced in my experiments through `Run().log_image` function, as paths. Any time I try to open them in the dashboard, it seems stuck on loading, but actually fails with 404.

![image](https://user-images.githubusercontent.com/1897842/95581384-3abfe400-0a39-11eb-8fdc-a15de01dd5e6.png)

![image](https://user-images.githubusercontent.com/1897842/95581345-267be700-0a39-11eb-8127-71a24c636175.png)

### To reproduce

Just run the below component and add the image to the dashboard.

```
---
version: 1.1
kind: component
tags: [examples]
name: bug

run:
  kind: job
  container:
    image: python:3.7
    command:
    - /bin/bash
    - -c
    args:
    - |
        apt-get update && apt-get install -y -q gcc python3-dev \
        && pip install polyaxon==1.1.9 --no-cache-dir \
        && wget https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png \
        && python -c 'from polyaxon.tracking import Run; Run().log_image("googlelogo_color_272x92dp.png")'
```

### Expected behavior

The Google logo should appear in the dashboard.

### Environment

- Polyaxon 1.1.9
- Python 3.7

You have all the details in the component definition.
