### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by rogerzklotz** [polyaxon/polyaxon#113]
Hello! Looks like a great project, thanks for all your work!

I am following along with the docs.polyaxon.com installation instructions, and ran into an issue where I'm not able to login. I am on gcloud, successfully deployed polyaxon (got the message with instructions), verified the ip address for the load balancer was correct, and updated my config.yml to use the load balancer.

config.yml looks like:
```
polyaxonSecret: "random_string"

user:
  username: "rogerklotz"
  email: "someemail@mailinator.com"
  password: "simplePASS)WORD"

serviceType: LoadBalancer
```
Output when I login:
```
Starting new HTTP connection (1): 35.X.X.X
    
Could not login.

None on http://35.X.X.X:80/api/v1/users/token/.
```

I'm not sure what other commands I should run to show you the status of the cluster, etc. Any thoughts on what I should do? I'm afraid I'm not very experienced with Kubernetes or polyaxon, so I'm not sure where the problem lies. I think with a nudge in the right direction I should be able to figure it out.
