### ISSUE TITLE
Returning from being familiar with 0.4

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#1161]
### Unclear documentation
I used to do project upload and then specify path to a dockerfile. Not seeing any examples from the recent documentation. 
What is the new process for doing that? 

Didn't find an example run throught the polyaxon-cli
### Missing Documentation

polyaxon upload

**Comment by polyaxon-team** [comment]
related #887

**Comment by hollowgalaxy** [comment]
good read @polyaxon-team but not sure what the conclusion of that convo was... nor do I know where to look for documentation for that solution.

**Comment by mouradmourafiq** [comment]
An upload command, with similar behavior as in v0, will be merged next week I think.

**Comment by hollowgalaxy** [comment]
Thanks... in the meantime I'll use the remote github branch... but I'm not able to launch the experiment (or at least what it was called before)
polyaxonfile.yml
```
---
version: 1.1
kind: component

inputs:
  - {name: region, type: str, isOptional: true, value: us-west-2}
  - {name: batch_size, type: int, isOptional: true, value: 8}
  - {name: max_epochs, type: int, isOptional: true, value: 300}
  - {name: learning_rate, type: float, isOptional: true, value: 0.00001}


run:
  kind: job
  init:
    - connection: "test"
      git: { revision: polyaxon }
      container:
        name: test_image
        image: src/polyaxon/test/Dockerfile
        resources:
          gpu:
            requests: 1
            limits: 1

        command: -e AWS_REGION={{ region }} \
           python src/polyaxon/test/experiment.py \
            --batch_size={{ batch_size }} \
            --max_learning_rate={{ learning_rate }} \
            --max_epochs={{ max_epochs }}
```
bayes.yml
```
---
version: 1.1
kind: operation


matrix:
  kind : bayes
  concurrency: 1
  numInitialRuns: 2
  maxIterations: 4
  metric:
    name: f1_score
    optimization: minimize
  utilityFunction:
    acquisitionFunction: ucb
    kappa: 2.576
    gaussianProcess:
      kernel: matern
      lengthScale: 1.0
      nu: 1.9
      numRestartsOptimizer: 0

  params:
      learning_rate:
        kind: 'linspace'
        value: '0.001:0.03:5'

pathRef: ./polyaxonfile.yml
```
command
```
polyaxon run -p test -f ./polyaxonfile.yml -f bayes.yml 
```
error
```
Creating a new run...
Could not create a run.
Error message: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.14.2', 'Date': 'Sat, 14 Nov 2020 16:42:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '127', 'Connection': 'keep-alive', 'Allow': 'GET, POST, HEAD, OPTIONS', 'X-Frame-Options': 'DENY', 'Vary': 'Origin, Cookie', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin'})
HTTP response body: ["You cannot create this operation, your account has reached the allowed quota or does not support operations of kind: matrix"]
.
Statuts: 400. One or more request parameters is incorrect
```

also folder structure in repo
src
  - polyaxon
      -test
         -Dockerfile
         -bayes.yml
         -polyaxonfile.yml
         -experiment.py

**Comment by mouradmourafiq** [comment]
You are having an indetation issue, the container that you provided is overriding the default git container, you need to have main container for your job:

```yaml
---
version: 1.1
kind: component

inputs:
  - {name: region, type: str, isOptional: true, value: us-west-2}
  - {name: batch_size, type: int, isOptional: true, value: 8}
  - {name: max_epochs, type: int, isOptional: true, value: 300}
  - {name: learning_rate, type: float, isOptional: true, value: 0.00001}


run:
  kind: job
  init:
    - connection: "test"
      git: { revision: polyaxon }
  container:
    name: test_image
    image: src/polyaxon/test/Dockerfile
    resources:
      gpu:
        requests: 1
        limits: 1

    command: -e AWS_REGION={{ region }} \
       python src/polyaxon/test/experiment.py \
        --batch_size={{ batch_size }} \
        --max_learning_rate={{ learning_rate }} \
        --max_epochs={{ max_epochs }}
```

Polyaxon CE only provides grid/random/mapping in eager mode.
