### ISSUE TITLE
Blank screen when clicking on job

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#1163]
### Describe the bug
When going to the url provided in the terminal I get (there is a micro second blimp of seeing the ui, but too fast to see whats on it)
![image](https://user-images.githubusercontent.com/52365584/99151767-34cdac00-2652-11eb-8a7d-292464d525ce.png)
here is terminal output
![image](https://user-images.githubusercontent.com/52365584/99151790-5c247900-2652-11eb-962d-e203fa7b6fc4.png)

### To reproduce
Run a job.
``` 
polyaxon run -p test -f ./polyaxonfile.yml
```
content of polyaxonfile
```
---
version: 1.1
kind: component

inputs:
  - {name: region, type: str, isOptional: true, value: us-west-2}
  - {name: batch_size, type: int, isOptional: true, value: 8}
  - {name: max_epochs, type: int, isOptional: true, value: 100}
  - {name: learning_rate, type: float, isOptional: true, value: 0.00001}


run:
  kind: job
  init:
    - connection: "test-repo"
      git: { revision: polyaxon }
      container:
        name: test_image
        image: src/polyaxon/test/Dockerfile
        resources:
          gpu:
            requests: 1
            limits: 1

        command: -e AWS_REGION={{ region }} \
           python src/polyaxon/test/polyaxon/test/experiment.py \
            --batch_size={{ batch_size }} \
            --max_learning_rate={{ learning_rate }} \
            --max_epochs={{ max_epochs }}

```

### Expected behavior
Expecting to see the ui

Note: I recorded the screen to see what happens in the blimp at which it shows the ui and saw that the job failed. However don't see why (immediately fails, is my presumption)
