### ISSUE TITLE
Missing documentation for specifying path to dockerfile.

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#1164]
### Unclear documentation
In 0.4 I was able to specify path to the uploaded Dockerfile (via polyaxon upload). Now I'm using github branch feature to upload the code (yml file below)... However not seeing how to specify the dockefile path that is in the repo that was pulled. looking at (https://polyaxon.com/docs/core/specification/init/) gives not insight into the problem outside of copy pasting the docker file lines. which is very wonky.

```
---
version: 1.1
kind: component

inputs:
  - {name: region, type: str, isOptional: true, value: us-west-2}
  - {name: batch_size, type: int, isOptional: true, value: 8}
  - {name: max_epochs, type: int, isOptional: true, value: 300}
  - {name: learning_rate, type: float, isOptional: true, value: 0.00001}


run:
  kind: job
  init:
    - connection: test
      git: { revision: polyaxon }
  container:
    name: test_image
    image: src/polyaxon/test/Dockerfile # this line is clearly wrong... not sure where to specify dockerfile path to build image
    resources:
      gpu:
        requests: 1
        limits: 1

    command: -e AWS_REGION={{ region }} \
       python src/polyaxon/test/experiment.py \
        --batch_size={{ batch_size }} \
        --max_learning_rate={{ learning_rate }} \
        --max_epochs={{ max_epochs }}
```

https://polyaxon.com/docs/core/specification/init/
### Missing Documentation
not showing how to specify path to dockerfile

issue with using Dockerfile path that is in the repo

**Comment by hollowgalaxy** [comment]
I also tried the yml below, but it failed with the error
```
Polyaxonfile is not valid.
Error message: {'run': {0: {'container': ["Error initializing V1Container, __init__() got an unexpected keyword argument 'filename'"]}}}.
```
yml file
```
---
version: 1.1
kind: component

inputs:
  - {name: region, type: str, isOptional: true, value: us-west-2}
  - {name: batch_size, type: int, isOptional: true, value: 8}
  - {name: max_epochs, type: int, isOptional: true, value: 300}
  - {name: learning_rate, type: float, isOptional: true, value: 0.00001}


run:
  kind: job
  init:
    - connection: test
      git: { revision: polyaxon }
  container:
    name: test_image
    filename: src/polyaxon/test/Dockerfile
    resources:
      gpu:
        requests: 1
        limits: 1

    command: -e AWS_REGION={{ region }} \
       python src/polyaxon/test/experiment.py \
        --batch_size={{ batch_size }} \
        --max_learning_rate={{ learning_rate }} \
        --max_epochs={{ max_epochs }}
```

**Comment by polyaxon-team** [comment]
The container expects an image not a dockerfile. The `DockerfileType` is an initializer that create a dockerfile that you can create an image with using one of the components supported, see this build example: https://github.com/polyaxon/polyaxon-quick-start/blob/master/helpers/build.yml
Here's a documentation on how to build containers: https://polyaxon.com/docs/intro/quick-start/building-containers/

**Comment by hollowgalaxy** [comment]
@polyaxon-team  Not sure why this was closed as the question was not answered....
the question being... "Specifying path to the dockerfile." And the missing documentation about that. What is linked don't explain how to pass the Dockerfile to the yml for building the container....

**Comment by polyaxon-team** [comment]
Hey, you are passing a path to an image, the container does not expect a dockerfile.

If you need to build a new image, you need to either use the `DockerfileTyp` or provide a `dockerfile`. Assuming your git repo has a dockerfile, you can provide the context to one of the component for building the container image, or provide your own logic to build the container image.

Here's an example that does that https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/horovod/tensorflow/build.yaml

Since this example is using one of the privided components, both of them expect a context that contains a valid dockerfile, the operation passes that context based on the cloned git repo:

```yaml
  context:
    value: "/plx_context/artifacts/polyaxon-examples/horovod/tensorflow"
```

**Comment by hollowgalaxy** [comment]
@polyaxon-team I ran the build.yml based on the suggestion to use `context:`
```
Polyaxonfile is not valid.
Error message: Received unexpected params `{'context'}`.
``` 
build.yml
```
version: 1.1
kind: operation
name: build
params:
  context:
    value: /plx-context/artifacts/test
runPatch:
  init:
  - connection: "test"
    git: { revision: polyaxon }
  - dockerfile:
      image: test_image:latest
      filename: src/polyaxon/test/Dockerfile


pathRef: ./polyaxonfile.yml
```
So I specified workdir and Dockefile full path and that worked (in a sense that i got passed the previous errors) (build.yml below),
however now seems docker for some reason is trying to pull the image test_image (as the logs on kubectl mentions). Which doesn't make sense, since I'm trying to build the image with that name
```
version: 1.1
kind: operation
name: build
runPatch:
  init:
  - connection: "test"
    git: { revision: polyaxon }
  - dockerfile:
      image: test_image:latest
      workdir: /plx-context/artifacts/test
      filename: /plx-context/artifacts/test/src/polyaxon/test/Dockerfile

pathRef: ./polyaxonfile.yml
```
