### ISSUE TITLE
Can't pull docker from azure container registry.

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#1168]
### Describe the bug
Tried using dockerfile, possible gave up. Using docker registry... acr seems to not connect and I keep getting "Job has reached the specified backoff limit".

Created the secret with
```
kubectl create secret docker-registry acr --namespace polyaxon --docker-server=<docker repo>
 --docker-username=<service account id> --docker-password=<service account password>
```

build.yml
```
version: 1.1
kind: operation
name: build

runPatch:
  init:
  - connection: "test"
    git: { revision: polyaxon }

component:
  run:
    kind: job
    environment:
      imagePullSecrets: ['acr']
    container:
      image: polyaxontest.azurecr.io/polytest:latest
      command: echo "done building"
```

### Expected behavior
successfully deploy/build docker

**Comment by polyaxon-team** [comment]
>Tried using dockerfile, possible gave up. 

All the polyaxonfiles you linked in the issues were wrong, and they will not build any container.

>acr seems to not connect and I keep getting "Job has reached the specified backoff limit".

Please try the same config with the image pull secret outside of Polyaxon on a simple pod:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: test
      image:  polyaxontest.azurecr.io/polytest:latest
      command: echo "done building"
   imagePullSecrets:
     - name: acr
```
