### ISSUE TITLE
UI to support basepath to work with ingress path other then /

### ISSUE THREAD

**Issue by omerfsen** [polyaxon/polyaxon#1170]
### Current behavior
When we configure ingress for certain subdir. Application itself needs to comply with that

So a sample ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: polyaxon
    meta.helm.sh/release-namespace: polyaxon
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/component: polyaxon-api
    app.kubernetes.io/instance: polyaxon-1.3.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: polyaxon-polyaxon-ingress
    app.kubernetes.io/part-of: polyaxon-core
    app.kubernetes.io/version: 1.3.2
    heritage: Helm
    release: polyaxon
  name: polyaxon-polyaxon-ingress
  namespace: polyaxon
spec:   
  rules:
  - host: services.dev-aimlinference.com
    http:
      paths:
      - backend:
          serviceName: polyaxon-polyaxon-gateway
          servicePort: 80
        path: /polyaxon(/|$)(.*)
  tls:
  - hosts:
    - services.dev-aimlinference.com
    secretName: aimlinference-tls
```

so even we do that on the source code of https://services.dev-aimlinference.com/polyaxon/ we get basehref as '/' so application (UI) also needs to conform to that.

![image](https://user-images.githubusercontent.com/29705627/99529381-9c0f9700-2997-11eb-87d1-aa58973f20d6.png)

**Comment by polyaxon-team** [comment]
```yaml
ui:
  baseUrl: "/foo"  # default "/'
```

**Comment by omerfsen** [comment]
Hi 

I see 1.4.0 helm chart released but on values.yaml file we still dont see

```yaml
ui:
  baseUrl: "/foo"  # default "/"
```

Although you defined it

https://github.com/polyaxon/polyaxon/blob/master/charts/polyaxon/templates/proxies-cm.yaml
```yaml
# UI
  {{- if (not (eq (.Values.ui.enabled | toString) "<nil>")) }}
  POLYAXON_UI_ENABLED: {{ .Values.ui.enabled | quote }}
  {{- end }}
  {{- if (not (eq (.Values.ui.adminEnabled | toString) "<nil>")) }}
  POLYAXON_UI_ADMIN_ENABLED: {{ .Values.ui.adminEnabled | quote }}
  {{- end }}
  {{- if .Values.ui.offline }}
  POLYAXON_UI_OFFLINE: {{ .Values.ui.offline | quote }}
  {{- end }}
  {{- if .Values.ui.assetsVersion }}
  POLYAXON_UI_ASSETS_VERSION: {{ .Values.ui.assetsVersion | quote }}
  {{- end }}
  {{- if .Values.ui.baseUrl }}
  POLYAXON_UI_BASE_URL: {{ .Values.ui.baseUrl | quote }}
  SCRIPT_NAME: {{ .Values.ui.baseUrl | quote }}
  {{- end }}
```

**Comment by omerfsen** [comment]
I just installed the 1.4.0 polyaxon with helm chart:

base_href is now using path i provide but script is not:

![image](https://user-images.githubusercontent.com/29705627/101769140-6f562780-3ade-11eb-871f-f2e726fc9a5a.png)


I see SCRIPT env variable is also populated:


**kubectl get cm -n polyaxon polyaxon-polyaxon-proxies-config -o yaml**
```yaml


apiVersion: v1
data:
  POLYAXON_DNS_USE_RESOLVER: "true"
  POLYAXON_HOST: http://polyaxon-polyaxon-gateway:80
  POLYAXON_PROXY_API_HOST: polyaxon-polyaxon-api
  POLYAXON_PROXY_API_PORT: "80"
  POLYAXON_PROXY_API_USE_RESOLVER: "true"
  POLYAXON_PROXY_STREAMS_HOST: polyaxon-polyaxon-streams
  POLYAXON_PROXY_STREAMS_PORT: "80"
  POLYAXON_SSL_ENABLED: "true"
  POLYAXON_SSL_REDIRECT_ENABLED: "false"
  POLYAXON_UI_ADMIN_ENABLED: "true"
  POLYAXON_UI_BASE_URL: /polyaxon
  POLYAXON_UI_ENABLED: "true"
  SCRIPT_NAME: /polyaxon
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: polyaxon
    meta.helm.sh/release-namespace: polyaxon
  creationTimestamp: "2020-12-10T11:00:54Z"
  labels:
    app.kubernetes.io/component: polyaxon-config
    app.kubernetes.io/instance: polyaxon-1.4.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: polyaxon-polyaxon-proxies-config
    app.kubernetes.io/part-of: polyaxon-core
    app.kubernetes.io/version: 1.4.0
    heritage: Helm
    release: polyaxon
  name: polyaxon-polyaxon-proxies-config
  namespace: polyaxon
  resourceVersion: "12127"
  selfLink: /api/v1/namespaces/polyaxon/configmaps/polyaxon-polyaxon-proxies-config

```

**Comment by mouradmourafiq** [comment]
This is tricky, we will check that and see if we can fix it, I am not sure honestly how many changes are required for the sub-path.

> I see 1.4.0 helm chart released but on values.yaml file we still dont see

We define a generic UI section: `ui: {}`

**Comment by mouradmourafiq** [comment]
Can you add the following option on the ui section as well:
```yaml
ui:
  baseUrl: /polyaxon/
  staticUrl: static/
```
the `/` are important.
