### ISSUE TITLE
argFormat is not applied to the resulting configuration

### ISSUE THREAD

**Issue by gmrukwa** [polyaxon/polyaxon#1188]
### Describe the bug

I followed [this instruction](https://polyaxon.com/docs/core/specification/io/#argformat) and while the value seems to be properly assigned in the `argFormat`, it is not applied in the resulting configuration.

### To reproduce

```
version: 1.1
kind: operation
name: bug

component:
  version: 1.1
  kind: component
  name: bug

  inputs:
  - name: dummy
    isOptional: true
    value: true
    type: bool
    argFormat: "{{ 'dummy-var' if dummy else 'var' }}"

  run:
    kind: job
    container:
      image: alpine
      args: ["echo", "{{ params.dummy.as_arg }}"]

```

### Actual behavior

Compiled specification for `polyaxon run -f bug.yml -P dummy=True`:
```
version: 1.1
kind: compiled_operation
name: bug
inputs:
  - name: dummy
    type: bool
    value: true
    isOptional: true
    argFormat: dummy-var
run:
  kind: job
  init: []
  container:
    args:
      - echo
      - '--dummy'
    image: alpine
    name: polyaxon-main
```

Compiled specification for `polyaxon run -f bug.yml -P dummy=False`:
```
version: 1.1
kind: compiled_operation
name: bug
inputs:
  - name: dummy
    type: bool
    value: false
    isOptional: true
    argFormat: var
run:
  kind: job
  init: []
  container:
    args:
      - echo
      - ''
    image: alpine
    name: polyaxon-main
```

### Expected behavior

Compiled specification for `polyaxon run -f bug.yml -P dummy=True`:
```
version: 1.1
kind: compiled_operation
name: bug
inputs:
  - name: dummy
    type: bool
    value: true
    isOptional: true
    argFormat: dummy-var
run:
  kind: job
  init: []
  container:
    args:
      - echo
      - 'dummy-var'
    image: alpine
    name: polyaxon-main
```

Compiled specification for `polyaxon run -f bug.yml -P dummy=False`:
```
version: 1.1
kind: compiled_operation
name: bug
inputs:
  - name: dummy
    type: bool
    value: false
    isOptional: true
    argFormat: var
run:
  kind: job
  init: []
  container:
    args:
      - echo
      - 'var'
    image: alpine
    name: polyaxon-main
```

### Environment

Polyaxon CLI  version: 1.3.5
Polyaxon Agent Version: 1.3.4
