### ISSUE TITLE
Operation stays in the created state if the input of a component is of type any

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1212]
### Describe the bug
Operation stays in the created state if the input of a component is of type any. When I change the type to str, the operation continues to execute as expected.

![Screenshot from 2021-01-14 13-03-57](https://user-images.githubusercontent.com/1316069/104616381-fdd34100-5668-11eb-9613-5b6b45f6283f.png)

### To reproduce

```
version: 1.1
kind: operation
name: test_merge_files
joins:
  - query: 'status: succeeded|failed, pipeline: UUID'
    limit: 300
    params:
      files:
        value: artifacts.outputs
        contextOnly: true
pathRef: ./components/merge.yaml
component:
  version: 1.1
  kind: component
  name: Merge
  description: Merge many results
  inputs:
    - name: files
      type: any
      isList: true
  outputs:
    - name: result
      type: path
      value: results
      isOptional: true
  run:
    kind: job
    init:
      - artifacts:
          dirs: '{{files}}'
    container:
      command:
        - bash
        - '-c'
        - >-
          echo "done."
      image: IMAGE
      name: polyaxon-main
      workingDir: WORKING_DIR


```
### Expected behavior
An error message or that the operation continues processing.
