### ISSUE TITLE
Internal Ingress unreachable in AWS

### ISSUE THREAD

**Issue by Ph4rell** [polyaxon/polyaxon#1224]
### Describe the bug
Hello guys,

I already setup Polyaxon on an EKS cluster and succeed to reach it with port forward. But now i'm facing some difficulties to make it reachable to my teammates via an AWS ALB.

Here my Polyaxon config.yaml:
```
ingress:
  enabled: true
  hostName: xxx.yyy
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    external-dns.alpha.kubernetes.io/hostname: xxx.yyy
    kubernetes.io/ingress.class: alb

gateway:
  service:
    type: ClusterIP
```
As you can see i'm using AWS ALB Ingress Controller to manage the creation of the AWS ALB and external-dns to manage the route53 records creation.

The polyaxon deployment goes well, the ALB is created, pointing on a target group with the pod gateway inside but i can't reach polyaxon through the DNS of the ALB or the route53 DNS.

I checked all the AWS parts, everything looks good to me, did i missed something ? I tried another config with `target-type to instance` and `gateway type to NodePort` and got the same result.

However everything works fine when i setup the ALB in internet-facing mode.

If someone already setup the kind of architecture could help !

Regards,
Pierre

### Environment
AWS EKS version 1.18
External-DNS version 0.7.3
aws-alb-ingress-controller version 2.1.0

**Comment by polyaxon-team** [comment]
When you deploy with `alb.ingress.kubernetes.io/scheme: internal`, can you port-forward the traffic from Polyaxon's gateway to `localhost` just to test that everything works as expected, basically this will just validate that the API is healthy and is responsive.

**Comment by Ph4rell** [comment]
@polyaxon-team yes the command `polyaxon port-forward` works in local.

**Comment by polyaxon-team** [comment]
So the issue is from the ingress to the gateway.

Can you use `path: /*` instead of the default value `/`.

```yaml
ingress:
  path: /*
```

**Comment by polyaxon-team** [comment]
It also looks similar to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1325
Hopefully the suggestion above will work.

**Comment by Ph4rell** [comment]
I set the value for the path but still got the same problem. Indeed it looked like the Issue #1325 ...
Maybe i will open an issue at https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues what do you think ?
Here the running Ingress config.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: xxx.yyy
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: polyaxon
    meta.helm.sh/release-namespace: polyaxon
  finalizers:
  - ingress.k8s.aws/resources
  generation: 1
  labels:
    app.kubernetes.io/component: polyaxon-api
    app.kubernetes.io/instance: polyaxon-1.5.4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: polyaxon-polyaxon-ingress
    app.kubernetes.io/part-of: polyaxon-core
    app.kubernetes.io/version: 1.5.4
    heritage: Helm
    release: polyaxon
  name: polyaxon-polyaxon-ingress
  namespace: polyaxon
spec:
  rules:
  - host: polyaxon.datalab.ehda.co
    http:
      paths:
      - backend:
          serviceName: polyaxon-polyaxon-gateway
          servicePort: 80
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - hostname: internal-k8s-polyaxon-polyaxon-b4ec570d59-654030662.eu-central-1.elb.amazonaws.com

```
