### ISSUE TITLE
Could not connect to remote server

### ISSUE THREAD

**Issue by Ph4rell** [polyaxon/polyaxon#1228]
### Describe the bug
Hi,

i got the below error when i try to run the experimentation sample:

```
polyaxon run --url=https://raw.githubusercontent.com/polyaxon/polyaxon-quick-start/master/experimentation/simple.yaml -l
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053b0c40>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/installation
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053c91c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/installation
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053c92b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/installation
Could not connect to remote server to fetch installation version.
Creating a new run...
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054d0820>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/default/test/runs
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054d08e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/default/test/runs
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054d0a30>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/v1/default/test/runs
Could not create a run.
Error message: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/default/test/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054d0b80>: Failed to establish a new connection: [Errno 61] Connection refused')).
```
### To reproduce
Here my polyaxon config file: 
```
ingress:
  enabled: true
  hostName: xxx.yyy
  path: /*
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    external-dns.alpha.kubernetes.io/hostname: xxx.yyy
    kubernetes.io/ingress.class: "alb"

gateway:
  service:
    type: ClusterIP

postgresql:
  enabled: false

externalServices:
  postgresql:
    user: "foo"
    password: "foobarbaz"
    database: "db"
    host: 10.67.3.98
    port: 5432

ui:
  adminEnabled: true
```

i'm using a public certificate in AWS ACM and use the certificate discovery of the AWS LoadBalancer Controller to automatically bind the certificate to the ALB. (https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/cert_discovery/)

As the certificate is public, I cannot enter the certificate and the key in a secret, and I wonder if the problem is not there?
Except that everyting is working properly, i can access my polyaxon in HTTPS, do i need to work with port-forward to launch some runs ?
