### ISSUE TITLE
Container polyaxon-api failed liveness and readiness

### ISSUE THREAD

**Issue by Ph4rell** [polyaxon/polyaxon#1232]
### Describe the bug
Hi @polyaxon-team, could you help me with this issue, i saw there was previous issues about the same but can't find a solution.

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  10m                     default-scheduler  Successfully assigned polyaxon/polyaxon-polyaxon-api-57868c69fd-jhhgz to ip-10-67-3-131.eu-central-1.compute.internal
  Normal   Pulling    10m                     kubelet            Pulling image "polyaxon/polyaxon-api:1.5.4"
  Normal   Pulled     9m43s                   kubelet            Successfully pulled image "polyaxon/polyaxon-api:1.5.4" in 18.842610087s
  Normal   Created    9m43s                   kubelet            Created container polyaxon-api
  Normal   Started    9m43s                   kubelet            Started container polyaxon-api
  Warning  Unhealthy  3m48s (x10 over 8m18s)  kubelet            Liveness probe failed: Get "http://10.67.3.176:80/healthz/": dial tcp 10.67.3.176:80: connect: connection refused
  Normal   Killing    3m48s                   kubelet            Container polyaxon-api failed liveness probe, will be restarted
  Warning  Unhealthy  3m42s (x11 over 8m42s)  kubelet            Readiness probe failed: Get "http://10.67.3.176:80/healthz/": dial tcp 10.67.3.176:80: connect: connection refused
```
Nothing relevant with logs from the container.
```
k logs -n polyaxon polyaxon-polyaxon-api-57868c69fd-jhhgz                                                                            192.168.1.227 ip | 87.89.197.22 ip 
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
```

I set this variables like describe in others issues with same problem but didn't change anything.
```
k exec -n polyaxon polyaxon-polyaxon-api-57868c69fd-jhhgz -- env | grep -i intervals_compatibility                                   192.168.1.227 ip | 87.89.197.22 ip 
POLYAXON_INTERVALS_COMPATIBILITY_CHECK=-1
```

```
k get pods -n polyaxon                                                                                                               192.168.1.227 ip | 87.89.197.22 ip 
NAME                                          READY   STATUS    RESTARTS   AGE
polyaxon-polyaxon-api-57868c69fd-jhhgz        0/1     Running   2          19m
polyaxon-polyaxon-gateway-9ff979444-xmjr4     1/1     Running   0          19m
polyaxon-polyaxon-operator-5bfcd9c499-s6qw8   1/1     Running   0          19m
polyaxon-polyaxon-streams-6574fd7c44-lvxwc    1/1     Running   0          19m
```

### Environment
EKS = 1.19
Coredns = 1.8.0
Polyaxon = 1.5.4

**Comment by polyaxon-team** [comment]
Hi @Ph4rell , how did you set the `compatibilityCheck` config option?

**Comment by Ph4rell** [comment]
In my config.yml file.
```
intervals:  
  compatibilityCheck: "-1"
```

**Comment by polyaxon-team** [comment]
can you share the complete config.yml, this might not be the root cause.

**Comment by Ph4rell** [comment]
Here my full config file, the file is a template used by Terraform to fill the different variables. And then i use Helm provider to deploy polyaxon (below Terraform code)
```
ingress:
  enabled: true
  hostName: ${hostname}
  extraPaths: 
  - path: /*
    backend:
      serviceName: ssl-redirect
      servicePort: use-annotation
  - path: /*
    backend:
      serviceName: forward
      servicePort: use-annotation
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"RedirectConfig":{"Host":"${hostname}","Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
    alb.ingress.kubernetes.io/actions.forward: '{"ForwardConfig":{"TargetGroups":[{"ServiceName":"polyaxon-polyaxon-gateway","ServicePort":"80"}]},"Type":"forward"}'
    external-dns.alpha.kubernetes.io/hostname: ${hostname}
    kubernetes.io/ingress.class: "alb"

gateway:
  service:
    type: ClusterIP

postgresql:
  enabled: false

externalServices:
  postgresql:
    user: ${db_username}
    password: ${db_password}
    database: ${db_name}
    host: ${db_ip}
    port: ${db_port}

ui:
  adminEnabled: true

artifactsStore:
  name: s3-artifacts
  kind: s3
  schema:
    bucket: "s3://${artifacts_bucket_name}/"
  secret:
    name: "${artifacts_secret_name}"

intervals: 
  compatibilityCheck: "-1"
```

```
resource "helm_release" "polyaxon" {
  name             = "polyaxon"
  namespace        = "polyaxon"
  create_namespace = true
  repository       = "https://charts.polyaxon.com"
  verify           = false
  version          = "1.5.4"
  chart            = "polyaxon"
  values           = [templatefile("${path.module}/config.yml.tpl",local.template_vars)]
}
```
