### ISSUE TITLE
Render whitespace correctly in logs viewer

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#1247]
### Describe the bug

Polyaxon experiments often use white space sensitive output to display tables or other information in the terminal. The Logs viewer in the UI uses `white-space=normal` which fails to display tables generated by Keras model summary or [`tabulate`](https://pypi.org/project/tabulate/).

This issue has been previously reported for Polyaxon v0 in #528 and has been fixed there, however it looks like it got re-introduced in v1.

### To Reproduce
Print [Keras model summary](https://keras.io/models/about-keras-models/#about-keras-models) or a [`tabulate`](https://pypi.org/project/tabulate/) table and observe that the output doesn't display whitespace correctly.
<img width="920" alt="Screenshot 2021-03-26 at 14 54 14" src="https://user-images.githubusercontent.com/13285808/112642296-71e94c80-8e43-11eb-8ba9-49ddf10cc8b6.png">

### Expected behavior
The Logs viewer should render whitespace correctly.

This can be easily implemented by adding the following CSS properties:
```css
.euiDataGridRowCell:not(.euiDataGridRowCell--controlColumn) .euiDataGridRowCell__content, .euiDataGridRowCell:not(.euiDataGridRowCell--controlColumn) .euiDataGridRowCell__truncate, .euiDataGridRowCell:not(.euiDataGridRowCell--controlColumn) .euiDataGridRowCell__expandContent {
    white-space: pre !important;
}
```
Which will result in the following output:
<img width="902" alt="Screenshot 2021-03-26 at 14 54 27" src="https://user-images.githubusercontent.com/13285808/112642491-a6f59f00-8e43-11eb-95ce-36d996da27e5.png">

### Environment

Polyaxon Cloud 1.7.4
