### ISSUE TITLE
Issue building docker image using example build config

### ISSUE THREAD

**Issue by minaadel** [polyaxon/polyaxon#1271]
### Describe the bug
Attempting to deploy the docker image build yaml file available under [https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/build_image/build-ml.yaml](url) using the polyaxon cli returns the following error:
```
>polyaxon run -f build_docker_image.yaml -l
Polyaxonfile is not valid.
Error message: The Polyaxonfile's version specified is not supported by your current CLI.Your CLI support Polyaxonfile versions between: 1.1 <= v <= 1.1.You can run `polyaxon upgrade` and check documentation for the specification..
```
### To reproduce
The contents of `build_docker_image.yaml`
```
version: 1.1
kind: operation
name: build
params:
  destination:
    connection: localreg
    value: polyaxon-examples:ml
runPatch:
  init:
  - dockerfile:
      image: python:3.8.8-buster
      run:
      - 'pip3 install --no-cache-dir -U polyaxon["polyboard"]'
      - pip3 install scikit-learn xgboost matplotlib vega-datasets joblib lightgbm xgboost
      langEnv: 'en_US.UTF-8'
hubRef: kaniko
```

### Expected behavior
A build operation should begin that results in an image being saved to the docker registry connected under destination: connection:
### Environment
Polyaxon 1.8.0
Polyaxon CLI 1.8.0

**Comment by mouradmourafiq** [comment]
Can you check if your environment has by any chance the legacy CLI also installed:

```
pip freeze | grep polyaxon
```

If it's the case, you need to uninstall the legacy libraries and only keep the new python library.

**Comment by minaadel** [comment]
These are the only two polyaxon libraries installed:
polyaxon==1.8.0
polyaxon-sdk==1.8.0

**Comment by mouradmourafiq** [comment]
Libraries installed are correct, I quickly tried and was not able to reproduce the file was submitted correctly.
We will check it on Monday.

**Comment by minaadel** [comment]
I can confirm that the same error appears using a freshly installed polyaxon 1.8.0 on the windows subsystem for linux (ubuntu) with the same file.

**Comment by minaadel** [comment]
@mouradmourafiq any updates? :)

**Comment by mouradmourafiq** [comment]
@minaadel sorry, completely forgot about this :)

I think it might be some formatting issues due to windows? Can you run `polyaxon check -f FILENAME.yaml`

Also you might copy the content to an editor to check if you are using spaces or tabs, I think yaml has issues with tabs.

**Comment by minaadel** [comment]
No issue, it happens :)

Here's the output of the check command.
```
>polyaxon check -f build_docker_image.yaml
Polyaxonfile is not valid.
Error message: The Polyaxonfile's version specified is not supported by your current CLI.Your CLI support Polyaxonfile versions between: 1.1 <= v <= 1.1.You can run `polyaxon upgrade` and check documentation for the specification..
```

The actual file itself uses 2 spaces per indentation, no tabs

**Comment by mouradmourafiq** [comment]
Very strange, and I could not reproduce. Did you try other files in the same examples folder https://github.com/polyaxon/polyaxon-examples/tree/master/in_cluster/build_image ?
Not sure if quoting all values would work on your system:
```yaml
version: 1.1
kind: operation
name: build
params:
  destination:
    connection: localreg
    value: "polyaxon-examples:ml"
runPatch:
  init:
  - dockerfile:
      image: "python:3.8.8-buster"
      run:
      - 'pip3 install --no-cache-dir -U polyaxon["polyboard"]'
      - 'pip3 install scikit-learn xgboost matplotlib vega-datasets joblib lightgbm xgboost'
      langEnv: 'en_US.UTF-8'
hubRef: kaniko
```
Finally you may try with `polyaxon -v ...` to trigger some additional debug information.

**Comment by minaadel** [comment]
You're absolutely correct! 
Simply quoting all the values did indeed force a new build that was eventually pushed to my connection :)
Thank you very much!

One last question though (I can open a new issue with the question if you'd like), how am I supposed to pull that same image from the localreg connection from within a polyaxonfile with `kind: component` (the one I use to run the usual experiments) ?

**Comment by mouradmourafiq** [comment]
I am not sure how you declared the registry and what type of registry you are using, but you will need something like `image: url/image:tag`, for instance if you are trying the in-cluster registry (https://polyaxon.com/integrations/in-cluster-registry/) the image should be:

```yaml
run:
  container:
    iamge: 172.30.0.8:31320/name:latest
```

If you are using GCR, the url will be the full GCR url with the image name and tag.

**Comment by minaadel** [comment]
I use the microk8s built in docker registry enabled via
`microk8s enable registry`
this I then connected with polyaxon by using the following snippet in my polyaxon_config file that I pass to helm.
```
connections:
  - name: localreg
    kind: registry
    schema: 
      url: 10.152.183.135:5000
```
The entire reason I'm trying to use a named connection is to abstract from having to use the particular ip of the registry when submitting a job to the polyaxon instance.
It's why I came to use the following snippet for the build operation
```
params:
  destination:
    connection: localreg
    value: "docker_img"
```
and wanted to do something similar with the component operation (experiment run).
