### ISSUE TITLE
GPU experiment, Insufficient nvidia.com/gpu

### ISSUE THREAD

**Issue by jakeret** [polyaxon/polyaxon#128]
I'm trying to run an experiment that should run on a GPU. However, none of the pods can be deployed because of `Insufficient nvidia.com/gpu`.

I've followed the installation instruction for the [GKE setup](https://docs.polyaxon.com/tutorials/gke_deployment/kubernetes_on_gke/) and created the node pool using `--accelerator "type=nvidia-tesla-p100,count=1"`. Additionally, I made sure to setup [GKE for GPU usage](https://cloud.google.com/kubernetes-engine/docs/concepts/gpus#installing_drivers).
When I look at the node details I see that the node have the  `nvidia.com/gpu: "1" capacity`

Any hint what could cause the `Insufficient nvidia.com/gpu` problem?

My `polyaxonfile.yml` looks like this:

```
---
version: 1

kind: experiment

environment:
  resources:
    cpu:
      requests: 1
      limits: 1
    gpu:
      requests: 1
      limits: 1
    memory:
      requests: 512
      limits: 2048
      
declarations:
  batch_size: 128
  learning_rate: 0.001
  dropout: 0.25
  num_epochs: 10

run:
  image: tensorflow/tensorflow:1.7.1-gpu-py3
  build_steps:
    - pip3 install --no-cache-dir -U polyaxon-helper
    - pip3 install --no-cache-dir -U  keras
  env_vars:
    - ['LD_LIBRARY_PATH', '/usr/local/nvidia/lib64']
  cmd: python3 finefood/run.py
```

**Comment by mouradmourafiq** [comment]
Hi @jakeret I am not sure what is the problem, could be related to this issue https://github.com/NVIDIA/k8s-device-plugin/issues/33

**Comment by wbuchwalter** [comment]
@jakeret Are all the pods failing or just some of them? A GPU can only be assigned to a single pod at the same time (Kubernetes does not support GPU sharing), so could it be that you don't have enough GPUs in your cluster to support all the pods at the same time?

**Comment by jakeret** [comment]
Thx for the reply. 
At the moment I'm trying to run one experiment on a cluster with 4 GPUs. So there should be enough resources available. I'm running the cluster with P100 and in the docs K80 were used. Could this cause some problems?

@mouradmourafiq the issue looks very similar. But I'm not quite sure how/where to run the `docker pull nvidia/k8s-device-plugin:1.9` mentioned there. Do you have any hints?

**Comment by mouradmourafiq** [comment]
@jakeret two things you can do to check if it's a problem related to Polyaxon.

You can just schedule a pod on your cluster that requires GPU:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
        limits:
          nvidia.com/gpu: 1 
  restartPolicy: Always
```
You can also try to schedule with `alpha.kubernetes.io/nvidia-gpu: 1` and see if it works.
If the pod cannot be scheduled than this is something related to the cluster and not Polyaxon.

Second thing is to check the k8s version, `kubectl version`, and check if Polyaxon discovered the system correctly, `polyaxon cluster` and dive into the node with GPU `polyaxon cluster -n ...`.
