### ISSUE TITLE
connection in services

### ISSUE THREAD

**Issue by nayeem8527** [polyaxon/polyaxon#1352]
### Describe the bug
I am creating a jupyter notebook service with volume_claim connection, but I think it is not mounting the database with the notebook.

### To reproduce
persistent volume yml file : 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset-pvc-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
    #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "datasets"
  claimRef:
    namespace: polyaxon
    name: dataset-pvc-1
```

volume claim yaml file:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataset-pvc-1
  namespace: polyaxon
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
```
polyaxon config file:

```
artifactsStore:
  name: demo-volume
  kind: volume_claim
  schema:
    mountPath: "/tmp/outputs"
    volumeClaim: "polyaxon-pvc-artifacts"

connections:
  - name: data-1
    kind: volume_claim
    schema:
      mountPath: "datasets"
      volumeClaim: "dataset-pvc-1"
```

service yaml file:

```
version: 1.1
kind: operation
component:
  version: 1.1
  kind: component
  name: notebook
  inputs:
    - name: image
      type: str
      value: jupyter/tensorflow-notebook
      isOptional: true
  run:
    kind: service
    init:
      - connection: data-1
        artifacts:
          dirs: ["datasets"]
    container:
      args:
        - '--no-browser'
        - '--ip=0.0.0.0'
        - '--port={{globals.ports[0]}}'
        - '--allow-root'
        - '--NotebookApp.allow_origin=*'
        - '--NotebookApp.trust_xheaders=True'
        - '--NotebookApp.token='
        - '--NotebookApp.base_url={{globals.base_url}}'
        - '--NotebookApp.notebook_dir={{globals.run_outputs_path}}'
        - '--LabApp.base_url={{globals.base_url}}'
      command:
        - jupyter
        - notebook
      image: '{{image}}'
      name: polyaxon-main
    ports:
      - 8888
```

### Expected behavior
It should display the database folder in jupyter notebook or when I type `! ls` from notebook, it should display the content.

### Environment
1. Everything is in linux
2.  Created a single worker node kubernetes cluster.
