### ISSUE TITLE
Allow setting DAG outputs without the SDK/Client

### ISSUE THREAD

**Issue by polyaxon-team** [polyaxon/polyaxon#1413]
### Current behavior

Currently users who need to set outputs on a DAG need to use the SDK/Client to push an outputs from an operation to the parent pipeline. 
A recurrent question is similar to this [slack thread](https://polyaxon.slack.com/archives/C6QBND2SV/p1631032033004100?thread_ts=1629127492.032500&cid=C6QBND2SV)

> is there a similar way to make one of the outputs of ops in a dag as the output of the dag?

```
outputs:
  - name: dag_output
    ref: ops.dag_operation_1
    value: outputs.dag_operation_1_output_name
```

### Enhancement

Allow users to pass outputs/results to the pipeline directly from the Polyaxonfile specification.
