### ISSUE TITLE
connection usage unclear

### ISSUE THREAD

**Issue by lr87** [polyaxon/polyaxon#1421]
I want to use "connection" module to mount the host path to the docker container.
Although there have been documentation about the "connection" [https://polyaxon.com/docs/setup/connections/](url) but there's no more detailed instruction.
I refered to the [https://github.com/polyaxon/polyaxon/blob/master/core/tests/fixtures/samples/artifaction_location.yaml](url), and wrote my polyaxonfile:
```
version: 1.1
kind: component
tags: [examples]

run:
  kind: job

  connections:
    - name: foo
      kind: host_path
      hostPath: /home/peter/data
      mountPath: /dataset

  container:
    image: classfication_pytorch1.9:v2
    command: ["/bin/sh", "-c"]
    args: ["nvidia-smi; pwd; ls /dataset"]
```

But it came an error:
```
Polyaxonfile is not valid.
Error message: {'run': {0: {'connections': {0: ['Not a valid string.']}}}}.
```
I tried to move the "connection" settings out of "run" settings (after "tags"), but it did not work.

So, would you help me to get the "connection" settings work? Thank you.

**Comment by polyaxon-team** [comment]
Hi @lr87 the `connections` definition should go in your config deployment file. So you have to update your `config.yaml` with the connections that you want the platform to be aware of and run an upgrade.

Once the deployment is done, you can then start using the connection in your jobs/services:

```yaml
version: 1.1
kind: component
tags: [examples]

run:
  kind: job

  connections: [foo, ...]
...
```

The link that you mentioned is for setup, here is the link to author the job specification: https://polyaxon.com/docs/experimentation/jobs/specification/#connections
