### ISSUE TITLE
Does Community UI has Admin dashboard?

### ISSUE THREAD

**Issue by HaoLiuHust** [polyaxon/polyaxon#1458]
I have setup a community self-hosted polyaxon, and the config abourt ui is 
```
ui:
  enabled: true
  offline: false
  adminEnabled: true
```
according to the documentation, if I set adminEnabled to true, there should be an admin dashboard. But I did not find it, there is no difference to turn it on/off
