### ISSUE TITLE
GPU experiment on GKE, Insufficient alpha.kubernetes.io/nvidia-gpu

### ISSUE THREAD

**Issue by laetitiae** [polyaxon/polyaxon#151]
Hello,

I want to run an experiment using GPU on GKE: GKE version 1.9.7-gke.3 and polyaxon version 0.1.2 (I tried with new versions of polyaxon too).
When I'm trying to run polyaxon-example with tensorflow + gpu, the pod plxjob-master0** can't be schedulable in any node because there is an error: "Insufficient alpha.kubernetes.io/nvidia-gpu"
![selection_086](https://user-images.githubusercontent.com/15209619/43281253-8692fdbe-9113-11e8-8422-03cc0233807b.png)

I check the pod, and the resources limits are expressed in this way:
![selection_089](https://user-images.githubusercontent.com/15209619/43281314-a6482cd8-9113-11e8-9690-4d0521758577.png)

Using kubectl, I can use my GPU resources but with the annotation nvidia.com/gpu. I read that on GKE documentation, you can't use alpha.kubernetes.io/nvidia-gpu annotation (not supported).
After look into the code, I see the POLYAXON_K8S_GPU_RESOURCE_KEY variable. This is a env variable on pod (plxjob-master0*).
![selection_087](https://user-images.githubusercontent.com/15209619/43281327-b0785f52-9113-11e8-9ac4-09f0eae46ccb.png)

How can I change this POLYAXON_K8S_GPU_RESOURCE_KEY variable using polyaxon configuration?

** Edit: polyaxon cluster -n 2:
![image](https://user-images.githubusercontent.com/15209619/43312481-b7a9564e-918d-11e8-837f-859c65dc3391.png)

Thanks in advance!

**Comment by mouradmourafiq** [comment]
Hi @laetitiae I believe that the issue you mentioned was solved in recent versions. 

I will try to reproduce it on a google cloud cluster with the same version 1.9.7-gke.3 during the weekend to make sure that the bug was fixed.

Can you tell me which new version did you try as well?

**Comment by laetitiae** [comment]
Hello @mouradmourafiq. 

Right now, I'm testing polyaxon 0.1.5 on GKE 1.10.5-gke.3.

Thanks!

**Comment by mouradmourafiq** [comment]
@laetitiae you are right it's a bug, I will try fix it today, and make a new release with the fix.

**Comment by laetitiae** [comment]
@mouradmourafiq, we were checking polyaxon-chart/polyaxon/templates/partials/_core.tpl , where this variable is set.
So the problem is Minor Version. 

We see your last commit. Thank you!

**Comment by mouradmourafiq** [comment]
@laetitiae Yes you can test it with the local chart, and I will make a new release by the end of the day.

**Comment by laetitiae** [comment]
@mouradmourafiq it doesn't work:
![image](https://user-images.githubusercontent.com/15209619/43320161-d0b090ca-91a7-11e8-87ab-717fdbf9d15a.png)

For now, we change _core.tpl as solution:
`- name: POLYAXON_K8S_GPU_RESOURCE_KEY
{{- if ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 8 }}
  value: "nvidia.com/gpu"
{{- else }}
  value: "alpha.kubernetes.io/nvidia-gpu"`

But it's not the best solution.

**Comment by mouradmourafiq** [comment]
@laetitiae thank you for the solution, the fix that I made is wrong, I fixed the templated based on your solutions, and this time tried it on both cluster with `+` sign and without:

```
Mourads-MacBook-Pro:polyaxon-chart mourad$  helm install --debug --dry-run polyaxon/ | grep nvidia
  nvidia:
  nvidia:
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
          value: "nvidia.com/gpu"
```
