### ISSUE TITLE
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition

### ISSUE THREAD

**Issue by PingYufeng** [polyaxon/polyaxon#1528]
### Describe the bug

root@~# polyaxon admin deploy -f polyaxon_config.yaml
Polyaxon `platform` deployment file is valid
Namespace `polyaxon` is ready
Polyaxon could not be installed
Error message: `helm` command ('helm', 'install', 'polyaxon', 'polyaxon/polyaxon', '--namespace=polyaxon', '-f', 'polyaxon_config.yaml') failed with exit status 1
stdout:

stderr:
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition

### To reproduce

I take it with the guide of 'Install Polyaxon on Kubernetes' , and I set the value of config from charts.

1. https://polyaxon.com/docs/setup/platform/
2. https://github.com/polyaxon/charts/blob/master/polyaxon/values.yaml

```yaml
deploymentChart: platform
deploymentType: kubernetes
namespace: polyaxon
limitResources: false


# Custom cluster dns setup
dns:
  backend: "coredns"

postgresql:
  # Whether to deploy a postgres server in-cluster.
  # To use an external postgres instance:
  #  * set enabled to False, to disable the in-cluster deployment
  #  * configure external postgresql required attributes in services.postgresql
  enabled: true
  connMaxAge: 60
  auth:
    enablePostgresUser: true
    username: polyaxon
    password: polyaxon
    database: polyaxon
    postgresPassword: polyaxon
    existingSecret: ""
  architecture: standalone
  service:
    ports:
      postgresql: 5432
  persistence:
    enabled: false
    size: 2Gi
  master:
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - "polyaxon-core"
              topologyKey: "kubernetes.io/hostname"


# Please do not change this value,
# if you want to provide a custom artifacts store, please use artifactsStore.
# This is used as a fallback when no artifactsStore is provided
#defaultArtifactsStore:
#  name: default-artifacts-store
#  kind: host_path
#  schema: { "hostPath": "/tmp/artifactsStore", "mountPath": "/artifactsStore" }

artifactsStore:
  name: default-artifacts-store
  kind: host_path
  schema: { "hostPath": "/tmp/artifactsStore", "mountPath": "/artifactsStore" }


intervals: # in seconds
  runsScheduler: 15
  operationsDefaultRetryDelay: 60
  operationsMaxRetryDelay: 3600
  compatibilityCheck: 1800

ui:
  enabled: true
  offline: false
  adminEnabled: false


```

polyaxon admin deploy -f polyaxon_config.yaml

### Expected behavior

polyaxon cannot deploy successfully!

### Environment
ubuntu18.04
Kubernetes v1.23.6
docker 20.10.7
helm 3.11.0
