### ISSUE TITLE
Use Dockerfile instead of pulling images from repositories when running an experiment.

### ISSUE THREAD

**Issue by wematan** [polyaxon/polyaxon#154]
### Feature motivation

When working on a specific training environment built in a docker image we sometimes base it on an existing image and add a some dependencies and files to the image by building a docker image from a docker file.

### Feature description

polyaxonfile should include a dockerfile item in the build section. 
the image: will be the name of the new image that will be created from the dockerfile.
exmaple:
```
---
version: 1

kind: experiment

declarations:
  lr: 0.01
  batch_size: 128

build:
  dockerfile: path-to-dockerfile
  image: myown_tensorflow
  build_steps:
    - pip install -r polyaxon_requirements.txt

run:
  cmd: python3 train.py --batch-size={{ batch_size }} --lr={{ lr }}
```
