### ISSUE TITLE
Use Configmaps and envFrom instead of including partials

### ISSUE THREAD

**Issue by maver1ck** [polyaxon/polyaxon#158]
### Feature motivation

Including partials in every deployment makes deployment yamls very big and difficult to check on change (`helm diff`)

### Feature description

We can use configmaps and envFrom instead of including partials.

### Feature implementation

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
Unfortunately there is no option to use secrets in cm, so this remains as it is.

**Comment by mouradmourafiq** [comment]
Thanks for the suggestion, I think the best way to approach this is to mount the config map and the secret as volumes. And optionally give the user the possibility to mount extra config maps and secrets, this will help with resolving the issue of exposing secrets needed for integrations, it will be very useful for #150.

**Comment by mouradmourafiq** [comment]
@maver1ck just for reference, I implemented the change as you suggested, including the config maps as volumes is a bit overhead in terms of parsing the values on the app side, it could be done in the future, but for now I think your proposition is better.

I also wanted to mention that you can use secret in `fromEnv`, so basically this is how it works:

```yaml
envFrom:
- configMapRef:
    name: {{ template "polyaxon.fullname" . }}-config
- secretRef:
    name: {{ template "polyaxon.fullname" . }}-secret
```
