### ISSUE TITLE
Data and outputs settings validation

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#168]
### Describe the bug

Config parsing is currently not robust and fails silently, letting erroneous settings to be used by the platform.

### To Reproduce

Providing this data persistence config:

```yaml
persistence:
  data:
    mountPath: "/data/2"
    existingClaim: "data-2-pvc"
```
Will pass silently and raise Attribute issues during the scheduling.

### Expected behavior

The platform should notify the user that the settings is wrong. Ideally, a parser should be used before deploying the platform.
