### ISSUE TITLE
ReadOnly persistent volume not respected

### ISSUE THREAD

**Issue by sahewat** [polyaxon/polyaxon#199]
When using an attached persistent volume with the read-only flag an error is thrown during an experiment run and the sidecar shows that said volume is mounted with `read-only: false`
## Helm Configuration (snippet):
```
persistence: 
  data:
    data1:
      existingClaim: polyaxon-pvc-persistent-hazard
      mountPath: /persistent-hazard
      readOnly: true
```
## Experiment Permission:
```
Volumes:
  data1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  polyaxon-pvc-persistent-hazard
    ReadOnly:   false
```
