### ISSUE TITLE
Allow naming of experiments based on template

### ISSUE THREAD

**Issue by wbuchwalter** [polyaxon/polyaxon#230]
### Feature motivation
Having ids for default experiment names is a good default behavior but UX could be improved by name templating.

### Feature description

In the configuration file for an experiment or a group, users should be able to specify a named template, for example:

```yaml
kind: group

hptuning:
  matrix:
    learning_rate:
      linspace: 0.001:0.1:5
    activation:
      values: [relu, sigmoid]

name: model-v2-{{ learning-rate }}-{{activation}}

[...]
```
This would make the experiment group view much cleaner as I can know what an experiment is doing without having to click on it.
CLI commands also become easier to use.

This name could be appended to the experiment/group id to avoid conflicts.
