### ISSUE TITLE
Monitoring GPU stats not working

### ISSUE THREAD

**Issue by timorohner** [polyaxon/polyaxon#259]
### Describe the bug

Monitoring a running experiment that makes use of a GPU via the command `polyaxon experiment -xp EXPERIMENT_ID resources -j JOB_ID --gpu` results in an error messages that no job with GPUs has been found. Based on my initial assessment this seems to be a more general issue. A quick look at the database reveals that:

- The cluster nodes that have GPUs are correctly recognized as having GPUs. Entries in `Cluster Nodes` have a correct value for `N gpus`.
- However, no entries are to be found in `Node GPUs`

Additionally, installing the polyaxon-gpustat package in the experiment itself and adding a simple `print(polyaxon_gpustat.query())` confirms that the gpu is properly recognized and available. 

### To Reproduce
I've ran into this issue with various experiments. The easiest way to reproduce it is to use the tensorflow Cifar10 example provided here: https://github.com/polyaxon/polyaxon-examples/blob/master/tensorflow/cifar10/polyaxonfile_gpu.yml

I've modified the yaml file as follows:

```
---
version: 1

kind: experiment

environment:
  node_selector:
    gpu: v100
  resources:
    gpu:
      requests: 1
      limits: 1

build:
  image: tensorflow/tensorflow:1.4.1-gpu
  build_steps:
    - pip install --no-cache-dir -U polyaxon-helper
    - pip install --no-cache-dir -U polyaxon-gpustat

run:
  cmd:  python run.py --num-gpus=1 --train-steps=400
```

Additionally I added the following line at the end of `run.py`:

```
print(polyaxon_gpustat.query())
```

### Expected behavior
`polyaxon experiment -xp EXPERIMENT_ID resources -j JOB_ID --gpu` should properly monitor the gpu used in the experiment.

### Environment

Version 0.2.9 of polyaxon running on Google cloud. Experiments are run on a node-pool that consists of machines with 1x V100 GPUs, and I make use of the autoscaling feature provided by google to scale from 0 to as many machines as needed based on how many experiments are running. An issue encountered with this setup has been described earlier in a different issue (https://github.com/polyaxon/polyaxon/issues/243), which can be fixed as mentioned in that comment. My suspicion is that the particulars of my environment (in particular the autoscaling of the GPU instance node-pool) cause issues with the resource monitor daemon that is running on each polyaxon machine.
