### ISSUE TITLE
No nodes in cluster and experiments fail to build

### ISSUE THREAD

**Issue by jonathanlimsc** [polyaxon/polyaxon#274]
I deployed Polyaxon on Minikube (Mac) and am trying to run experiments using the polyaxon quickstart repo (https://github.com/polyaxon/polyaxon-quick-start.git). However, the experiment build keeps failing, and running 'polyaxon cluster' shows no nodes:

Cluster info:

--------------  ----------------------------------------
major           1
minor           10
compiler        gc
platform        linux/amd64
build_date      2018-03-26T16:44:10Z
git_commit      fc32d2f3698e36b93322a3465f63a14e9f0eaead
go_version      go1.9.3
git_version     v1.10.0
git_tree_state  clean
--------------  ----------------------------------------

When I run 'kubectl get pods --all-namespaces', this is the output

NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
kube-system   coredns-c4cffd6dc-42gcs                         1/1     Running   0          23h
kube-system   etcd-minikube                                   1/1     Running   0          23h
kube-system   kube-addon-manager-minikube                     1/1     Running   0          23h
kube-system   kube-apiserver-minikube                         1/1     Running   0          23h
kube-system   kube-controller-manager-minikube                1/1     Running   0          23h
kube-system   kube-dns-86f4d74b45-652fq                       3/3     Running   0          23h
kube-system   kube-proxy-npxr5                                1/1     Running   0          23h
kube-system   kube-scheduler-minikube                         1/1     Running   0          23h
kube-system   kubernetes-dashboard-6f4cfc5d87-p2z4j           1/1     Running   0          23h
kube-system   storage-provisioner                             1/1     Running   0          23h
kube-system   tiller-deploy-778f674bf5-xhmsv                  1/1     Running   0          23h
polyaxon      polyaxon-docker-registry-78d5499fc9-4wm69       1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-api-7b97bb447d-jl6h6          2/2     Running   0          5h
polyaxon      polyaxon-polyaxon-beat-77fb6cccc7-lmdhw         2/2     Running   0          5h
polyaxon      polyaxon-polyaxon-events-79c8ff59d9-2rqcq       1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-hpsearch-9b5589f5-874n5       1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-k8s-events-697cf8bb65-mnjz8   1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-logs-7bf467999-b8755          1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-monitors-57db4f7cd7-7x2j5     2/2     Running   0          5h
polyaxon      polyaxon-polyaxon-resources-glgwq               1/1     Running   0          5h
polyaxon      polyaxon-polyaxon-scheduler-76ccf9d665-xb9bg    1/1     Running   0          5h
polyaxon      polyaxon-postgresql-78d4cff55c-jhcvz            1/1     Running   0          5h
polyaxon      polyaxon-rabbitmq-6448d76c84-vp5ll              1/1     Running   0          5h
polyaxon      polyaxon-redis-688468649b-tg6qp                 1/1     Running   0          5h

I have also tried running 'helm update' and upgraded polyaxon to the latest release (0.3.2). How can I troubleshoot this?

**Comment by mouradmourafiq** [comment]
@jonathanlimsc you can look at the helm ci it's uses a minikube to run the chart tests.
@VinayTeki I think your issue is that you should enable rbac, because the cluster you are running is using rbac, Polyaxon cannot function correctly without having the right access.

**Comment by jonathanlimsc** [comment]
@mouradmourafiq Do you mind elaborating abit more?

**Comment by mouradmourafiq** [comment]
@jonathanlimsc this is the [config](https://github.com/polyaxon/polyaxon-chart/blob/master/ci/test-config.yml) used to do an end to end test on Minikube

You can try it yourself and see. Just be aware that the point of this config is to test that platform deploys and schedules jobs, but nothing more, you should not expect it to be a functionning deployment for real life use-cases.

**Comment by VinayTeki** [comment]
@mouradmourafiq Thanks a lot. That worked well. 
But this led me to another issue. The experiment takes forever to start.
Cluster specifications are good enough. 3 nodes, 12 cores, 15 gb ram 
```bash
Experiment info:

----------------  -------------------------
id                1
unique_name       root.quick-start.1
user              root
name
experiment_group
build_job         root.quick-start.builds.1
last_status       starting
created_at        9 minutes ago
updated_at        9 minutes ago
started_at        7 minutes ago
finished_at
total_run
is_clone          False
has_tensorboard
num_jobs          1
tags
ttl
```

And the logs just say `starting...` although the build was successful.

**Comment by mouradmourafiq** [comment]
@VinayTeki did you check the GKE dashboard to see if the pod is schedulable.

**Comment by VinayTeki** [comment]
@mouradmourafiq 
GKE dashboard shows the pods are scheduled.
![screenshot from 2018-11-29 17-28-02](https://user-images.githubusercontent.com/23612210/49220539-7d0b4980-f3fc-11e8-9025-09a29477f838.png)

**Comment by mouradmourafiq** [comment]
@VinayTeki can you stop that experiment and start a new one?

**Comment by VinayTeki** [comment]
@mouradmourafiq 
Stoping the previous experiement and running a different experiment gave the same results `polyaxon run -u -f polyaxonfile_declarations.yml`

**Comment by VinayTeki** [comment]
@mouradmourafiq 
yeah I did from the GUI and created a standard cluster.
Do you need any specific logs that can help identify the problem. Also the standard cluster didnot allow me to use the host disk in read-write mode. That is the reason I had to mount persistantVolumeClaims which seemed a little odd to me.

**Comment by mouradmourafiq** [comment]
You can use the host disk for testing, you need to use `/tmp` to mount the volumes.

I would suggest the following, if possible, delete the current cluster and create a new one with the following config:

 * Default node pool: 1 instance with 4vcpus and add label : `polyaxon -> core`
 * Another node pool: use the type of instances you want to use for experiments/buidls ... and use the lable : `polyaxon -> experiments`

For polyaxon config you can use the following:

```yaml
rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

user:
  password: the randompassofyourchoice

nodeSelectors:
  core:
    polyaxon: core
  experiments:
    polyaxon: experiments
  builds:
    polyaxon: experiments
  jobs:
    polyaxon: experiments
  tensorboards:
    polyaxon: experiments

# be aware that you cannot access the outputs from the ui because it's on the host of each node, that's why we generally ask users to use MultiReadWrite volume. Also not that to use the host nodes we are using `/tmp/...`

persistence:
  logs:
    existingClaim:
    mountPath: "/tmp/logs"
    hostPath: "/tmp/logs"
  repos:
    existingClaim:
    mountPath: "/tmp/repos"
    hostPath: "/tmp/repos"
  outputs:
    outputs:
      mountPath: "/tmp/outputs"
      hostPath: "/tmp/outputs"
  data:
    data:
      mountPath: "/tmp/data"
      hostPath: "/tmp/data"
```

**Comment by mouradmourafiq** [comment]
> Also the postgres pod still logs some the same error messages. I'm not sure if this is something to be worried about.

I don;t think that's still being logged that's probably logged at first, some pods might try to access the db before it's initialized.

**Comment by VinayTeki** [comment]
@mouradmourafiq Thanks. I'll test the configuration you suggested and finalize the issue.

**Comment by mouradmourafiq** [comment]
one last question how did you create the PVCs?

**Comment by VinayTeki** [comment]
I've created using the command:
`kubectl apply -f volume_config.yaml`
and the config file looked like this (Instead of one volume, I created five of those for five paths) 
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polyaxon-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
