### ISSUE TITLE
Decalarations of type list are not handled correctly in UI (overview and tables)

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#298]
### Describe the bug
Using the following declaration:

```yaml
version: 1

kind: experiment

declarations:
  param1: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

run:
  cmd: python --param1="{{ param1 }}"
```
 will result in a parm1 being a list, but the UI does not handle that correctly. 

Same thing for groups:

```yaml
version: 1

kind: experiment

hptuning:
  matrix:
    param1:
      values: [[32], [32, 32], [128], [128, 128]]

run:
  cmd: python --param1="{{ param1 }}"
```

The cli returns the correct representation:

<img width="841" alt="screenshot 2018-12-18 at 18 27 37" src="https://user-images.githubusercontent.com/1261626/50172724-edb7ce80-02f5-11e9-9fc5-725f96fa859e.png">

but the UI does a concatenation:

<img width="1256" alt="screenshot 2018-12-18 at 18 52 23" src="https://user-images.githubusercontent.com/1261626/50172781-1344d800-02f6-11e9-9800-3a60f1c8ddde.png">
