### ISSUE TITLE
Polyaxonfile is not valid - Error message 'a must be 1-dimensional'.

### ISSUE THREAD

**Issue by bfabiandev** [polyaxon/polyaxon#305]
If I specify the following
```
hptuning:
  concurrency: 4
  matrix:
    hidden_sz:
      values: [[32, 32], [128, 128]]
```
with the hack (`--hidden_sz="{{hidden_sz}}"`) it fails when I run it with the following error:
```
Polyaxonfile is not valid


Error message 'a must be 1-dimensional'.
```
The error seems to only appear if I only offer options of length 2. If I add `[32]` in front, the yaml file becomes valid and the experiments run. Any suggestions on what could be done in this case?
