### ISSUE TITLE
Support Jupyter Lab as a notebook environment

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#310]
### Feature motivation
Some people probably want to use not only jupyter notebook, but also jupyter lab.

### Feature description
It seems that the command to launch `jupyter notebook` is hard corded right now. We may be able to offer the feature to choose `jupyter notebook` or `jupyter lab`. 

https://github.com/polyaxon/polyaxon/blob/f072b325f3becc00ceab40f56737b94cea341ce5/polyaxon/scheduler/spawners/notebook_spawner.py#L83

#### Risks
An user potentially make a mistake to launch `jupyter lab` with an environment which doesn't have jupyter lab. But it is not critial to the user experience.

**Comment by yu-iskw** [comment]
I understand. I would love to contribute to that, but it sounds nice to wait for your redesigning the part. I look forward to seeing it. Thanks as always!

**Comment by mouradmourafiq** [comment]
Will be part of the v0.3.9
```yaml
---
version: 1

kind: notebook

environment:
  backend: lab

build:
  image: tensorflow/tensorflow:1.12.0-py3
  build_steps:
    - pip3 install jupyterlab==0.33.12
```
I pinned the `0.33.12` because some newer versions have some style issues.

**Comment by yu-iskw** [comment]
Awesome! Thank you for implementing the new feature.

**Comment by zewelor** [comment]
Hi

I'm trying that but get error:

```
Current cli version: 0.4.2.


Supported cli versions:

--------------  -----
latest_version  0.4.2
min_version     0.4.2
--------------  -----
polyaxon notebook start  -f polyaxon/notebook.yml

✗ Polyaxonfile is not valid.

Error message `{'environment': {'backend': ['Unknown field.']}}`.
```

```
version: 1

kind: notebook

environment:
  backend: lab

build:
  image: continuumio/miniconda3:4.5.12
  build_steps:
    - conda install -c anaconda gcc_linux-64 && ln -s /opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc /usr/bin/gcc
    - conda env update -n base -f polyaxon_conda_env.yml
    - pip install jupyterlab
```
