### ISSUE TITLE
Can't use TPU

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#362]
### Describe the bug
I tried to use Cloud TPU. But I got the error on StackDriver logging. And the experiment was failed. It seems that we need to specify tensorflow version with annotation.

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: admission webhook \"pod-init.cloud-tpus.google.com\" denied the request: TensorFlow version must be specified in annotation \"tf-version.cloud-tpus.google.com\" for pod requesting Cloud TPUs","reason":"InternalError","details":{"causes":[{"message":"admission webhook \"pod-init.cloud-tpus.google.com\" denied the request: TensorFlow version must be specified in annotation \"tf-version.cloud-tpus.google.com\" for pod requesting Cloud TPUs"}]},"code":500}
```

#### YAML
```
---
version: 1

kind: experiment

environment:
  resources:
    cpu:
      requests: 4
      limits: 4
    memory:
      requests: 15000
      limits: 15000
    tpu:
      requests: 8
      limits: 8

build:
  image: tensorflow/tensorflow:1.12.0
  build_steps:
    - pip install --no-cache-dir -r requirements.txt

run:
  # this is just a dummy python file.
  cmd: python test.py
```

#### requirements.txt
```
polyaxon-client==0.3.8
polyaxon-cli==0.3.8
jupyter
google-cloud-storage
```

### Expected behavior
We can create a TPU.

### Environment
- Polyaxon: 0.3.8

## Links
- https://cloud.google.com/tpu/docs/kubernetes-engine-setup
- https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_k8s.yaml#L28

**Comment by mouradmourafiq** [comment]
Sorry about that, should be fixed for next release with possible customization, during deployment you can set the follwoing options in your config:
 * tpuTensorflowVersion: to set the tensorflow version, default `1.12`
 * tpuResourceKey: to set the resource key, default ` cloud-tpus.google.com/v2`, you can change this to use the preemptible-v2.

**Comment by yu-iskw** [comment]
Alright. I look forward to the next release! Thank  you for your great works as always.

**Comment by mouradmourafiq** [comment]
Would you mind trying this pod manifest, and see if it succeeds for you? `kubectl create -f filename.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    tf-version.cloud-tpus.google.com: "1.12"
spec:
  containers:
  - args:
    - echo scheduled
    command:
    - /bin/bash
    - -c
    image: gcr.io/tensorflow/tpu-models:r1.12
    name: polyaxon-experiment-job
    resources:
      limits:
        cloud-tpus.google.com/preemptible-v2: "8"
      requests:
        cloud-tpus.google.com/preemptible-v2: "8"
  - args:
    - echo sidecar
    command:
    - /bin/sh
    - -c
    image: ubuntu
    name: polyaxon-job-sidecar
  initContainers:
  - args:
    - echo init
    command:
    - /bin/sh
    - -c
    image: ubuntu
    name: polyaxon-job-init
```

**Comment by yu-iskw** [comment]
I tried it, but I got the error.
```
The Pod "" is invalid: metadata.name: Required value: name or generateName is required
```

**Comment by mouradmourafiq** [comment]
True, Updated the manifest

**Comment by yu-iskw** [comment]
I could submit the YAML file. It seems that a TPU was created and the output looks as expected. But the pod status is `CrashLoopBackOff`.
```
$ kubectl create -f test.yml

$ kubectl logs somejob -c polyaxon-experiment-job
scheduled

$ gcloud compute tpus describe gke-us-decent-polyaxon-ce9c85ad-tpu-2b0bd9e6 --zone=us-central1-b
acceleratorType: v2-8
cidrBlock: 10.20.48.0/29
createTime: '2019-02-14T19:10:38.301313402Z'
health: HEALTHY
ipAddress: 10.20.48.2
labels:
  goog-gke-tpu: ''
name: projects/professor-x-dev/locations/us-central1-b/nodes/gke-us-decent-polyaxon-ce9c85ad-tpu-2b0bd9e6
network: global/networks/default
networkEndpoints:
- ipAddress: 10.20.48.2
  port: 8470
port: '8470'
schedulingConfig:
  preemptible: true
serviceAccount: service-305320364537@cloud-tpu.iam.gserviceaccount.com
state: READY
tensorflowVersion: '1.12'

$ kubectl get pods
NAME      READY   STATUS             RESTARTS   AGE
somejob   0/2     CrashLoopBackOff   10         9m
```

**Comment by mouradmourafiq** [comment]
ok thanks, just to make sure, because for me it stays pending for long. 

the real experiment pod is different.

**Comment by yu-iskw** [comment]
@mouradmourafiq I will try the fixed version in 0.3.9 later. Can you tell me an example of YAML file to set up TPU environment? I am looking into the code, but I haven't completely understand how to specify the TPU environment yet.

**Comment by mouradmourafiq** [comment]
your yaml file, the one in the first comment, should work. I am updating the docs with all new features of this version, should be live some time tomorrow.

**Comment by yu-iskw** [comment]
I got it. I would like to know especially how to pass annotation for tensorflow version and TPU resource key. I look forward to the documentation. I appriciate the great work!

**Comment by yu-iskw** [comment]
I am looking into them for YAML file.
- https://github.com/polyaxon/polyaxon/blob/5866bd258052c1a603f4bd33f7113f1499a794a1/polyaxon/polyaxon/config_settings/core.py#L9
- https://github.com/polyaxon/polyaxon/blob/ae999e0665555de9df80af270269bf76e6882c21/polyaxon/polyaxon/config_settings/spawner.py#L146

**Comment by mouradmourafiq** [comment]
Ah I see, `tpuTensorflowVersion` and `tpuResourceKey` in your deployment config file. those are the default values. It will be reflected in the docs ASAP.

**Comment by yu-iskw** [comment]
I have made sure that we can run an experiment with TPU by default on polyaxon 0.3.9. The job is inspired by the following ResNet example.

https://cloud.google.com/tpu/docs/tutorials/kubernetes-engine-resnet

```
---
version: 1

kind: experiment

environment:
  resources:
    cpu:
      requests: 8
      limits: 8
    memory:
      requests: 10000
      limits: 10000
    tpu:
      requests: 8
      limits: 8

build:
  image: gcr.io/tensorflow/tpu-models:r1.11
  env_vars:
    - ['PYTHONPATH', '/tensorflow_tpu_models/models']

run:
  cmd: python \
        /tensorflow_tpu_models/models/official/resnet/resnet_main.py \
        --data_dir="gs://cloud-tpu-test-datasets/fake_imagenet" \
        --model_dir="gs://xxxxxxxxxxx/resnet"
```

**Comment by yu-iskw** [comment]
Yes, we can.

**Comment by yu-iskw** [comment]
@mouradmourafiq Thank you for adding the documentaiton about custom TPU resources. But I don't clearly understand which level in the deployment config I should put the definition. I tried to put the top leven and under `environment`, but the YAML is not valid. I also trid to put it under `environment.resources` and `environment.resources.tpu`, but it created a regular TPU v2, not preemptible one.  Can you tell me how to pass that in detail? 

https://github.com/polyaxon/polyaxon/blob/master/docs/configuration/custom-run-environment.md#using-tpus

## Wrong YAML
```
environment:
  resources:
    cpu:
      requests: 16
      limits: 16
    memory:
      requests: 20000
      limits: 200000
    tpu:
      requests: 8
      limits: 8
    tpuTensorflowVersion: "cloud-tpus.google.com/preemptible-v2"
    tpuResourceKey: "1.12"
```
