### ISSUE TITLE
Still having issues with azurebatch

### ISSUE THREAD

**Issue by posix4e** [polyaxon/polyaxon#364]
### Describe the bug
I installed azure batch virtual kublet
I can launch tasks such as

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: samples-tf-mnist-demo
  name: samples-tf-mnist-demo
spec:
  template:
    metadata:
      labels:
        app: samples-tf-mnist-demo
    spec:
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azurebatch
        effect: NoSchedule
      containers:
      - name: samples-tf-mnist-demo
        image: microsoft/samples-tf-mnist-demo:gpu
        args: ["--max_steps", "500"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
      restartPolicy: OnFailure

```

No problem using azure batch , but In the newest and previous polyaxon release, jobs crash
### To Reproduce
Launch the polyaxon_gpu job adding
```


diff --git a/cifar-tensorboard/polyaxonfile_gpu.yml b/cifar-tensorboard/polyaxonfile_gpu.yml
index 6a870a7..bf92154 100644
--- a/cifar-tensorboard/polyaxonfile_gpu.yml
+++ b/cifar-tensorboard/polyaxonfile_gpu.yml
@@ -4,10 +4,18 @@ version: 1
 kind: experiment
 
 environment:
+  tolerations:
+  - key: virtual-kubelet.io/provider
+    operator: Equal
+    value: azurebatch
+    effect: NoSchedule
   resources:
     gpu:
       requests: 1
       limits: 1
+    requests:
+      memory: "250Mi"
+      cpu: "500m"
 
 build:
   image: tensorflow/tensorflow:1.4.1-gpu
(END)
```
$ kubectl -n polyaxon describe pods plxjob-master0-69ce8807086f4956b45e9e86a19b8d67   and you will see
```

Name:               plxjob-master0-69ce8807086f4956b45e9e86a19b8d67
Namespace:          polyaxon
Priority:           0
PriorityClassName:  <none>
Node:               virtual-kubelet/
Labels:             app=polyaxon-experiment
                    experiment_group_name=
                    experiment_name=dev.test.4
                    experiment_uuid=69ce8807086f4956b45e9e86a19b8d67
                    job_uuid=0b7084d99df04c8295da744712d3daa3
                    project_name=dev.test
                    project_uuid=1c89c48e23e54725b1e5e1c2f46ec81b
                    role=polyaxon-workers
                    task_idx=0
                    task_type=master
                    type=polyaxon-runner
Annotations:        <none>
Status:             Failed
Reason:             ProviderFailed
Message:            batch.TaskClient#Add: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\r\n  \"odata.metadata\":\"https://testgpu31.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\",\"code\":\"InvalidPropertyValue\",\"message\":{\r\n    \"lang\":\"en-US\",\"value\":\"The value provided for one of the properties in the request body is invalid.\\nRequestId:81e4a70a-7ac1-4225-8bfe-1dcd415800b1\\nTime:2019-02-16T20:27:54.0120652Z\"\r\n  },\"values\":[\r\n    {\r\n      \"key\":\"PropertyName\",\"value\":\"commandLine\"\r\n    },{\r\n      \"key\":\"Reason\",\"value\":\"Total size of commandLine cannot be more than 32768 characters\"\r\n    }\r\n  ]\r\n}" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string
IP:                 
Init Containers:
```

### Expected behavior
Loading the job properly
### Environment
Azure kubernetes with the azure virtual node for azurebatch
