### ISSUE TITLE
How to access S3 buckets that are configured under persistence.data

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#369]
### Unclear documentation
https://docs.polyaxon.com/integrations/data-on-s3/
Section "Access to data in your experiments/jobs"

### Missing Documentation
The section describes requirements in the job definition yaml, but its unclear how the bucket can be accessed from within the actual jobs code. 
Just to access it via boto3 (hoping that authentication would happen transparently) was my only guess but access was denied.

**Comment by AntonFriberg** [comment]
Hi!

I figured this out after some testing. Here is a simple example

`check.py`
```python
"""Base experiments that checks polyaxon s3 input and output integration"""
from datetime import datetime
from multiprocessing import Process
from polyaxon_client.tracking import (Experiment, get_data_paths,
                                      get_outputs_path)
from polystores.stores.manager import StoreManager

experiment = Experiment()
print(experiment.get_experiment_info())
print("Data paths: {}".format(get_data_paths()))
print("Outputs path: {}".format(get_outputs_path()))

store = StoreManager(path=get_data_paths()['cifar-10'])


print('Starting parallel download')
start_time = datetime.now()
d1 = Process(target=store.download_dir, args=('train', '/train'))
d2 = Process(target=store.download_dir, args=('valid', '/valid'))
d3 = Process(target=store.download_dir, args=('test', '/test'))
d1.start()
d2.start()
d3.start()
print('All download threads started')
d1.join()
d2.join()
d3.join()
time_elapsed = datetime.now() - start_time
print('Download time (hh:mm:ss.ms) {}\n'.format(time_elapsed))

experiment.outputs_store.upload_file('/code/check.py')
```

`polyaxonfile.yml`
```yaml
---
version: 1

kind: experiment

environment:
  persistence:
    data: ['cinic-10']

build:
  image: python:3.6-slim
  build_steps:
    - pip install --no-cache-dir -U 'polyaxon-client[s3]'

run:
  cmd: python check.py
```

The main issue is that polystores currently do not support the downloading of entire buckets only files or directories.

**Comment by AntonFriberg** [comment]
This is how the inputs and outputs are configured in the helm configuration.

```yml
persistence:
  data:
    cifar-10:
      store: s3
      bucket: s3://cifar-10
      secret: s3-secret
      secretKey: s3-secret.json
  outputs:
    outputs:
      store: s3
      bucket: s3://polyaxon-outputs
      secret: s3-secret
      secretKey: s3-secret.json
```
