### ISSUE TITLE
Can't launch notebook with TPU

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#379]
### Describe the bug
I am not able to launch notebook with TPU in polyaxon 0.3.9. The build was succeeded. But, a pod for the notebook didn't appear. Besides, I didn't see any created TPU.

### To Reproduce
This is the command that I tried to launch a notebok with TPU.
```
polyaxon notebook start -u -f polyaxon_notebook_tpu.yml
```

#### `polyaxon_notebook_tpu.yml`
```
---
version: 1

kind: notebook

environment:
  resources:
    cpu:
      requests: 16
      limits: 20
    memory:
      requests: 10000
      limits: 20000
    tpu:
      requests: 8
      limits: 8

build:
  image: tensorflow/tensorflow:1.12.0
  build_steps:
    - pip install --no-cache-dir -r requirements.txt
```

#### `requirements.txt`
```
polyaxon-client[gcs]==0.3.9
polyaxon-cli==0.3.9
tensorflow-datasets==1.0.1
jupyter
```

### Expected behavior
We can expect that notebook with TPU is launced.

### Environment
- polyaxon: 0.3.9
