### ISSUE TITLE
Use datadir in notebook

### ISSUE THREAD

**Issue by zewelor** [polyaxon/polyaxon#406]
Hi

Thanks for such a great project. I've got helm chart with persistance data configured. When running jupyterlab, is it possible to access that dir ? I can't see it in jupyters lab file browser, like its not mounted ? Or I'm doing something wrong ?

**Comment by mouradmourafiq** [comment]
Can you give more information about the type of your data persistence and number of nodes in your cluster?

**Comment by zewelor** [comment]
I've got only 1 node, and following helm chart settings for persistence:

```
persistence:
  data:
    default-data:
      mountPath: "/data"
      hostPath: "/tmp/data"
```
