### ISSUE TITLE
Encountering issue to pull private docker image from Dockerhub

### ISSUE THREAD

**Issue by martmull** [polyaxon/polyaxon#412]
### Unclear documentation
Hello,

Polyaxon is working fine when It pulls a public docker image stored on Dockerhub. 
However, it fails when it tries to pull it from a private repository on Dockerhub.

I followed [this documentation](https://github.com/polyaxon/polyaxon/blob/master/docs/configuration/private-registries.md) and I reinstalled Polyaxon adding the Dockerhub credentials in the `polyaxon_config.yaml` file such as:
```yaml
privateRegistries:
  - host: "https://registry-1.docker.io/v2/"
    user: "<USER_ID>"
    password: "<PASSWORD>"
```
but I can't make it work. It shows me this error:
![image](https://user-images.githubusercontent.com/29927851/55164677-61c30780-516c-11e9-8930-cbda39806411.png)

I also tried using this registry "https://index.docker.io/v1/", with and without the protocol, I always encounter the same issue. 

Do you have any idea why Polyaxon cannot access the private docker image? Or am I missing something?

Thank you very much,
and by the way, Polyaxon is awesome!
