### ISSUE TITLE
Make it possible to use a secret for a private registry password

### ISSUE THREAD

**Issue by shotarok** [polyaxon/polyaxon#421]
### Feature motivation

I manage a polyaxon cluster on the GKE with the helm. I'd like to integrate GCR with polyaxon. However, I manage a `values.yml` for the helm in a GitHub repository. I don't want to put a raw credential in the `values.yml`. Instead of the raw json, I'd like to use a secret for a private registry password.

ref.  https://docs.polyaxon.com/integrations/gcr/

### Feature description

One idea is to make it possible to pass `secret` and `secretKey` in the `privateRegistries` like the GCS integration.

```
privateRegistries:
  - host: "my.registry.com"
    user: "_json_key"
    secret: "gcr-secret"
    secretKey: "gcr-key.json"
```
