### ISSUE TITLE
Building fail because of pip connection error

### ISSUE THREAD

**Issue by DamienMatias** [polyaxon/polyaxon#442]
### Describe the bug
When launching an experiment, the building fail because pip can't establish a connection. 

> 2019-04-28 15:26:06 UTC -- Building: Collecting scikit-learn==0.19.2 (from -r requirements.txt (line 1))
2019-04-28 15:26:06 UTC -- Building: [91m  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe60fb9ea10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/scikit-learn/

### To Reproduce

For example, if I use the random forest example : 
https://github.com/polyaxon/polyaxon-examples/tree/master/in_cluster/sklearn/random_forest
and I just do a 
`polyaxon run -u` 
after having created the project and init the folder.

### Expected behavior
The pip install should work and building finished.

### Environment

I use a vanilla EKS cluster using ekstcl. Here's the config file I use : 

```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: polyaxon
  region: eu-west-1

nodeGroups:
  - name: polyaxon
    instanceType: m5.xlarge
    desiredCapacity: 2
```

After that I installed polyaxon using the helm chart and the following config.yaml

```
rbac:
  enabled: true

ingress:
  enabled: false

serviceType: LoadBalancer

postgresql:
  persistence:
    enabled: true
    size: 5Gi
```

# Intuition
In general this error come from a proxy but in EKS cluster I don't understand where it comes from. The cluster is vanilla so the networking of the cluster should be good. Maybe it comes from my Polyaxon installation but I don't see what's missing.
Thank you in advance :)

**Comment by mouradmourafiq** [comment]
Your config is simple and fine.

Can you create a busybox pod, and try to pip install from inside it?

**Comment by DamienMatias** [comment]
I created a Python3 pod and It worked

**Comment by mouradmourafiq** [comment]
can you update the `polyaxonfile.yaml` by updating the build backend to kaniko:
```
---
version: 1

kind: experiment

framework: scikit-learn

tags: [examples]

declarations:
  n_estimators: 3
  max_features: 3
  min_samples_leaf: 80

build:
  backend: kaniko
  image: python:2.7
  build_steps:
    - pip install --no-cache-dir -r requirements.txt

run:
  cmd: python -u model.py --n_estimators={{ n_estimators }} \
                          --max_features={{ max_features }} \
                          --min_samples_leaf={{ min_samples_leaf }}
```
