### ISSUE TITLE
docs/integrations/nginx.md annotations seem to be missing "nginx." as a prefix to the keys

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#476]
### URL

https://docs.polyaxon.com/integrations/nginx/

### Wrong Documentation
```
ingress:
  annotations:
    ingress.kubernetes.io/proxy-connect-timeout: "600"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    ingress.kubernetes.io/send-timeout: "600"
    ingress.kubernetes.io/proxy-body-size: 4G
```
according to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-timeouts
should be 
```
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    [...]
```

If you agree I'm happy to prepare a PR
