### ISSUE TITLE
boolean declarations in run template?

### ISSUE THREAD

**Issue by stratospark** [polyaxon/polyaxon#478]
Is it possible to pass boolean flags in the run.cmd templating system? I have some scripts that expose no parameter boolean arguments.
```
declarations:
  save: True

run:
  cmd: python experiment.py {{save}}    # should be: python experiment.py --save
```

https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/declarations/
