### ISSUE TITLE
[Polyaxon 0.5] Issue running Python -c commands from CLI

### ISSUE THREAD

**Issue by ajgreine** [polyaxon/polyaxon#497]
### Describe the bug
When attempting to run an experiment via the CLI that uses a command, of the format `python -c "<python command>"`, in the experiment's cmd spot the CLI throws the error:
```
Reason: ["[ErrorDetail(string='Received non valid specification config. Received non valid yaml: `{\\'version\\': 1, \\'kind\\': \\'experiment\\', \\'build\\': {\\'image\\': \\'continuumio/miniconda3\\'}, \\'run\\': {\\'cmd\\': [\\'python -c \"print(\\\\\\'Tweet tweet\\\\\\')\"\\']}}`', code='invalid')]"]
Error while creating experiment.: None
```
The yaml is valid though and can be run via the UI. The yaml also works in v0.4.4.

### To Reproduce
Try to run an experiment using the following yaml:
```yaml
version: 1

kind: experiment

build:
  image: continuumio/miniconda3

run:
  cmd:
    - python -c "print('Tweet tweet')"
```

### Expected behavior
Experiment is started using the given experiment yaml config via the CLI.

### Environment
Polyaxon cluster running in EKS
