### ISSUE TITLE
nodeSelector example

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#520]
Is there an example of adding a `nodeSelector` constraint to the config file? I think the syntax for this changed slightly (it used to be `nodeSelectors`). Here's what I had previously:

```
nodeSelectors:
    core:
      polyaxon: core
    experiments:
      polyaxon: experiments
    builds:
      polyaxon: builds
```

I'm trying to add a constraint so that the core services, builds and experiments aren't scheduled on the same nodes, to avoid instability.

**Comment by mouradmourafiq** [comment]
Yes the [node scheduling](https://docs.polyaxon.com/configuration/custom-node-scheduling/) has changed, on the chart it only applies to the core components, i.e. only the pods deployed and managed by the chart, the following snippet can be different depending component enabled in-cluster:

```yaml
nodeSelector:
  polyaxon: core
  
postgresql:
  nodeSelector:
    polyaxon: core

redis:
  master:
    nodeSelector:
      polyaxon: core
  slave:
    nodeSelector:
      polyaxon: core

rabbitmq-ha:
  nodeSelector:
    polyaxon: core
    
docker-registry:
  nodeSelector:
    polyaxon: core 
```

For the builds, jobs, experiments, notebooks, tensorboards, since it's not required during the deployment and it can be configured on cluster level or team level, it's in the UI, under settings:

<img width="391" alt="Screenshot 2019-07-22 at 14 13 23" src="https://user-images.githubusercontent.com/1261626/61631684-4b950600-ac8b-11e9-8f28-54f713e76671.png">

<img width="1424" alt="Screenshot 2019-07-22 at 14 15 47" src="https://user-images.githubusercontent.com/1261626/61631726-62d3f380-ac8b-11e9-8506-f09d9599d505.png">
