### ISSUE TITLE
https on GKE

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#523]
I'm a bit confused about how to setup https for Google Kubernetes Engine. I'm looking at the docs here: https://docs.polyaxon.com/configuration/ssl/

So far I've understood that I need to use nginx, and I need to set `serviceType: NodePort`. I'm also trying to use an ingress.

Should I be following the second set of instructions? If so, should I not be using an ingress?

**Comment by mouradmourafiq** [comment]
I see, it's a bit confusing, the first option is using an ingress, the second one is just the node port exposed directly to the public or inside an intranet but with SSL.
So nginx ingress has as a default value ClusterIp, meaning that ClusterIp would work in general. GKE does not work correctly with ClusterIp (that's why there's a note there, may be it should be a warning with a bit more explanation), and it will be restarting the service, so they recommend using a LoadBlancer as service type, see [here](https://cloud.google.com/community/tutorials/nginx-ingress-gke).

**Comment by honnibal** [comment]
Thanks for the quick reply as always.

I have it all working now. One thing that tripped me up was, your example `kubectl create secret` command was missing the `--namespace polyaxon` argument. So when you update that area of the docs, you probably want to fix that.

Future readers can find a (template for a) working example here: https://github.com/honnibal/spacy-pretrain-polyaxon/blob/92ddbd26240cf238acaa57c20bc45bedf869aa7d/terraform-gke/configs/polyaxon-config.yml.tmpl

The values are filled by this script: https://github.com/honnibal/spacy-pretrain-polyaxon/blob/92ddbd26240cf238acaa57c20bc45bedf869aa7d/terraform-gke/scripts/install-polyaxon

Btw, one thing I've removed from my config is the file-server, as I was having some problems with it, and it simplifies things a lot. I don't recall why I switched over to it in the first place. Should I want a file-server?

**Comment by mouradmourafiq** [comment]
I just looked at the config tmpl, I would suggest to schedule the deps on a node that does not handle any training workload, just to avoid any downtime, this could be the same `core` or any other node, 1 node `n1-standard-4` should be more or less fine for all of the core and deps:

```yaml
postgresql:
  nodeSelector:
    polyaxon: core

redis:
  master:
    nodeSelector:
      polyaxon: core
  slave:
    nodeSelector:
      polyaxon: core

rabbitmq-ha:
  nodeSelector:
    polyaxon: core
    
docker-registry:
  nodeSelector:
    polyaxon: core 
```

Not sure about what is the `file-server` option? you can always use the cli to validate the options:

```bash
polyaxon admin deploy -f config.yaml --check
```

**Comment by lgeiger** [comment]
@honnibal Glad you got it working.

For future readers, here is the setup we are using in GKE with Ingress and [Google managed SSL secrets](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) after some fiddling.
1. Create static IP using `gcloud compute addresses create polyaxon-example-ip --global`
2. Deploy managed certificate with `kubectl apply -f polyaxon-certificate.yaml -n=polyaxon`
   ```yaml
   apiVersion: networking.gke.io/v1beta1
   kind: ManagedCertificate
   metadata:
     name: polyaxon-example-certificate
   spec:
     domains:
       - polyaxon.example.com
   ```
3. Deploy Polyaxon using
   ```yaml
   serviceType: NodePort
   ingress:
     enabled: true
     hostName: polyaxon.example.com
     tls:
       - hosts:
           - polyaxon.example.com
     annotations:
       kubernetes.io/ingress.global-static-ip-name: polyaxon-example-ip
       networking.gke.io/managed-certificates: polyaxon-example-certificate
       domainName: polyaxon.example.com
       ingress.kubernetes.io/add-base-url: "true"
       ingress.kubernetes.io/rewrite-target: /
   ```
4. Setup DNS record to point to the IP address created in step 1
5. Unfortunately GKE Ingress doesn't support the `rewrite-target` annotation (see [here](https://stackoverflow.com/questions/45868569/gke-ingress-not-respecting-rewrite-rule)) so I needed to change the GKE ingress deployment spec from:
   ```yaml
   spec:
     rules:
     - host: polyaxon.example.com
       http:
         paths:
         - backend:
             serviceName: polyaxon-polyaxon-api
             servicePort: 80
           path: /
     tls:
     - hosts:
       - polyaxon.example.com
   ```
   to
      ```yaml
   spec:
     rules:
     - host: polyaxon.example.com
       http:
         paths:
         - backend:
             serviceName: polyaxon-polyaxon-api
             servicePort: 80
           path: /*
     tls:
     - hosts:
       - polyaxon.example.com
   ```
   @mouradmourafiq Maybe we should revisit https://github.com/polyaxon/polyaxon-chart/pull/42
