### ISSUE TITLE
Use monospaced font and correct whitespace in logs viewer

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#528]
### Describe the bug

Polyaxon experiments often use white space sensitive output to display tables or other information in the terminal. The Logs viewer in the UI uses a non-monospaced font and `white-space=nowrap` which fails to display tables generated by Keras model summary or [`tabulate`](https://pypi.org/project/tabulate/).

### To Reproduce
Print [Keras model summary](https://keras.io/models/about-keras-models/#about-keras-models) or a [`tabulate`](https://pypi.org/project/tabulate/) table and observe that the output doesn't display whitespace correctly.
![Bildschirmfoto 2019-07-24 um 17 22 52](https://user-images.githubusercontent.com/13285808/61810703-ba16c700-ae37-11e9-9c6f-c34e46cfeb9b.png)

### Expected behavior
The Logs viewer uses a monospaced font and renders whitespace correctly.

This can be easily implemented by adding the following CSS properties:
```css
.logs .logs-content p {
    white-space: pre;
    font-family: "Source Code Pro";  /* It probably makes sense to add fallbacks */
}
```
Which will result in the following output:
![Bildschirmfoto 2019-07-24 um 17 22 22](https://user-images.githubusercontent.com/13285808/61810721-c26f0200-ae37-11e9-8d3b-b29108a43aba.png)

### Environment
Polyaxon 0.5.3
