### ISSUE TITLE
Netron Integration for Serialized Graph Artifact Inspection

### ISSUE THREAD

**Issue by AffineParameter** [polyaxon/polyaxon#571]
### Feature motivation

A frequent use-case of mine is generating various serialized graph artifacts from model training, usually in `.pb` or `.onnx` formats. To inspect these, I am required to download them to my local machine, then upload them to Netron (https://lutzroeder.github.io/netron/), one tab for each artifact that I would like to compare. This is cumbersome and aggravating. 

### Feature description
<kbd>
  <img src="https://user-images.githubusercontent.com/10703027/64893756-84bf7600-d63d-11e9-9030-100c2ccafda7.png">
</kbd>

### Feature implementation

A new [output component](https://github.com/polyaxon/polyaxon/tree/57cb5e972c4c75e95fcc7562313a916fcfd71a06/client/src/components/outputs) is created to support visualization of supported serialized graph artifacts utilizing Netron (https://github.com/lutzroeder/netron). This is a heavy dependency, so some sort of embedding might be easier?

New [extension group](https://github.com/polyaxon/polyaxon/blob/25e5343548dcfe569a4f2ccd1aaff22a93f5cfef/client/src/constants/extensions.ts) called `GRAPH_EXTENSIONS` containing the following extensions Netron supports: ONNX (.onnx, .pb, .pbtxt), Keras (.h5, .keras), Core ML (.mlmodel), Caffe (.caffemodel, .prototxt), Caffe2 (predict_net.pb, predict_net.pbtxt), MXNet (.model, -symbol.json), TorchScript (.pt, .pth), NCNN (.param) and TensorFlow Lite (.tflite).

**Comment by mouradmourafiq** [comment]
I think this should be solve once we introduce the html capability, users then can save such artifact as html and view it inside polyaxon without introducing a dependency.

**Comment by lgeiger** [comment]
I think this would be very useful.

> I think this should be solve once we introduce the html capability, users then can save such artifact as html 

I am not sure if in the case of `netron` this is possible, since it requires additional javascript that might be prevented from being executed.

**Comment by mouradmourafiq** [comment]
Closed in #690, users can log [html files](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/tracking/__init__.py#L129) and in case the UI does not handle a specific file or extension, users can easily build a component dashboard using a notebook, streamlit, voila..., and run the component to display the file/visualization similar to a tensorboard with the protobuf files.

**Comment by mouradmourafiq** [comment]
I had similar question this morning about netron, I suggested a similar solution as the comment above, i.e. a custom component:
```yaml
version: 1.1
kind: component
name: netron
tags:
  - visualization
  - dashboards
inputs:
  - name: uuid
    type: str
  - name: model_path
    type: path
run:
  kind: service
  init:
    - artifacts:
        dirs:
          - '{{ uuid + '/outputs/' + path}}'
  container:
    args:
      - "pip install netron; netron {{ globals.artifacts_path + '/' + uuid + '/outputs/' + path}}"
    command:
      - sh
      - -c
    image: python:alpine3.7
  ports:
    - 8080
```
After the workshop I realized that the python cli is a dummy server that serves an HTML file and a couple of js/json files.

We will be introducing an integration for Netron in v1.8.1 (next week) directly in the UI, similar to how we render Markdown/Notebooks/Custom HTML/...

![Screenshot 2021-04-09 at 18 42 04](https://user-images.githubusercontent.com/1261626/114214550-bce78180-9964-11eb-9678-b63740815241.png)

The component can be still useful for other use cases.
