### ISSUE TITLE
403 Error When Logging Into 'root' User Through GKE

### ISSUE THREAD

**Issue by jordanra-miso** [polyaxon/polyaxon#588]
### Description

When using GKE with Polyaxon, we are unable to login to the web client with the correct root username and root password, as we will usually receive a 403 error, regardless of the `config.yml` contents. "Usually" means that some `config.yml` combinations instead lead to 500 errors, or infinite stalling with the three circles animation.

We are also not able to create new users. While the "register new user" button leads us to the correct web page, filling out the form does nothing. The `db_user` table is never updated.

We also can't login via the CLI, though we're not certain if these issues are related.

We suspect most of these issues are tied to the PostgreSQL pod failing and disconnecting, preventing Django from connecting and accessing the table. Sometimes the `db_user` table is completely empty--we're also not sure when or why this occurs, but we encountered a 403 error even if there is a root user entry.

Setting `serviceType` to `LoadBalancer` allows us to login via CLI sometimes, but when using the web interface we still receive Postgres errors (see below screenshots).

### Screenshots of Google Errors

![image](https://user-images.githubusercontent.com/51926391/66596556-f9f56c80-eb51-11e9-8efa-f78358280ede.png)

![image](https://user-images.githubusercontent.com/51926391/66596678-3032ec00-eb52-11e9-901b-5db314aa3d30.png)

![image](https://user-images.githubusercontent.com/51926391/66596773-50fb4180-eb52-11e9-88ad-94bb0f6d3efe.png)

### To Reproduce

1. Set up a scalable GKE cluster with n1-standard-4 machine type.
2. Ensure gcloud SDK is set up with the correct credentials
3. Run the following shell commands in shell

```
# See below for the environment
gcloud container clusters get-credentials standard-cluster-4
kubectl config current-context
kubectl create -f rbac_config.yaml
helm init --service-account tiller
helm repo add polyaxon http://charts.polyaxon.com
helm repo update
kubectl create namespace polyaxon
polyaxon admin deploy -f polyaxon_config.yaml
```

4. Go to the GKE Ingress page.
5. Follow the ingress URL.
6. Log in with the root username and password.

### Expected Behaviour

We expect that the Polyaxon would let us login to the root user via the web browser. We also expect that polyaxon would let us login via the CLI. In prior setups with microk8s, these functioned as expected. This appears to be a GKE/Polyaxon interfacing issue.

### Environment

Our `polyaxon_config.yaml` and our `rbac.yaml` are shown below:

```yaml
# --------------------------------------------------------------
# rbac_config.yaml:
# --------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```

```yaml
# ---------------------------------------------------------------
# polyaxon_config.yaml
# ---------------------------------------------------------------
rbac:
  enabled: true

ingress:
  enabled: true

# We've tried LoadBalancer, ClusterIP, NodePort.
serviceType: LoadBalancer

# We've toggled the following settings on and off. CLI is working with these off right now.
#user:
#  username: root
#  email: root@polyaxon.local
#  password: rootpassword

#postgresql:
#  persistence:
#    enabled: true
#    size: 5Gi
```

I know this is a huge one-man project, but our team has been struggling with this setup for a week. So thank you for your time reviewing this!
