### ISSUE TITLE
Concurrency issue while experiment logging from multiple processes

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#591]
### Describe the bug

There is a concurrency issue when user runs a code in distributed setting with configuration:
single node, multiple gpus.

### To Reproduce
script.py
```
import torch
import torch.distributed as dist
from polyaxon_client.tracking import Experiment

if __name__ == "__main__":
    from polyaxon_client.logger import configure_logger
    configure_logger(verbose=True)
    dist.init_process_group("nccl", init_method="env://")
    plx_exp = Experiment()
    if dist.get_rank() == 0:
        plx_exp.log_params(**{
            "pytorch version": torch.__version__,
        })

    params = {
        "train loader": 100 if dist.get_rank() == 0 else 101,
        "train loader batch size": 16,
        "seed": 12
    }

    if dist.get_rank() == 0:
        plx_exp.log_params(**{k: v for k, v in params.items() if "loader" not in k})

    if dist.get_rank() == 1:
        # Uncomment the following lines to fix concurrency loggig issue
        # import time
        # time.sleep(2.0)

        tag = "" if dist.get_world_size() < 2 else " (rank {})".format(dist.get_rank())
        new_params = {"{}{}".format(k, tag): v for k, v in params.items() if "loader" in k}
        print("rank {} - params: {} | new params: {}".format(dist.get_rank(), params, new_params))    
        plx_exp.log_params(**new_params)

    dist.destroy_process_group()
```

YAML
```
---
version: 1

kind: experiment

# Setup running node:
environment:
  resources:
      gpu:
        requests: 2
        limits: 2

build:
  image: pytorch/pytorch:latest
  build_steps:
  - pip install polyaxon-client

run:
  cmd:    
    - python -m torch.distributed.launch --nproc_per_node=2 script.py
```

### Expected behavior

We expect to get params:
```
pytorch version                             "1.2.0"
seed                                               12
train loader (rank 1)                       101 
train loader batch size (rank 1)     16
```
but we get only 
```
pytorch version                             "1.2.0"
seed                                               12
```
