### ISSUE TITLE
Custom COPY command in build of polyaxon configuration

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#593]
### Feature motivation
I would like to reuse scripts to install something when building a docker image on polyaxon. But we can use some specific files such as `requirements.txt` and so on. Polyaxon automatically identify the files and put `COPY` command before executing build steps. But I want to explicitly specify copied files before executing build steps. I know it might have a risk not to use docker build cache efficiently.

As well as, I understand `polyaxon_setup.sh` enables me to do the same. But, when experimenting machine learning models, we potentially use different setting up script at the same time. So, I would like to have multiple scripts.
https://docs.polyaxon.com/configuration/custom-run-environment/#installing-other-libraries-or-running-other-commands

### Feature description
```
...
  build:
    image: tensorflow/tensorflow:1.14.0-gpu-py3
    copy:
      - scripts/install.sh
    build_steps:
      - bash scripts/install.sh
```
