### ISSUE TITLE
Optional `collection` configuration, instead of `matrix`, for `hptuning` Experiment Groups

### ISSUE THREAD

**Issue by AffineParameter** [polyaxon/polyaxon#600]
I might have missed how to do this in the documentation, but I couldn't find anything similar. Apologies if I missed something relevant.

### Feature motivation

I often want to run 10s of experiments w/in a logical experiment group that consist of a **subset** of elements in the cartesian product of unique parameter settings defined by the `matrix` block. 

For example, let's say I want to run a study on a model with 5 free coefficients that can be either `0` or `1`. The `matrix` space contains 2^5 possible configurations and will require me to run each of them. If, however, I only care about configurations where the sum of coefficients is one (ie. only one is "on" and the rest are "off"), then I _should_ only have to run 5 experiments... but I can't do this. I _can_ run the 2^5 experiments with a `grid_search`, but I can't run my 5 experiments.

### Feature description

Hypothetical example experiment group config:
```yaml
version: 1

kind: group

hptuning:
  concurrency: 8
  collection:
    A: [1, 0, 0, 0, 0]
    B: [0, 1, 0, 0, 0]
    C: [0, 0, 1, 0, 0]
    D: [0, 0, 0, 1, 0]
    E: [0, 0, 0, 0, 1]

run:
  cmd: echo  {{ A }} {{ B }} {{ C }} {{ D }} {{ E }}
```
Would result in 5 launched experiments with the following output:

1. `1 0 0 0 0`
2. `0 1 0 0 0`
3. `0 0 1 0 0`
4. `0 0 0 1 0`
5. `0 0 0 0 1`

I'm not convinced that this is the _right_ way to handle this, but the current system would be much more powerful if I could specify what points in the search space I am interested in.
