### ISSUE TITLE
Failed to fetch logs - GCS

### ISSUE THREAD

**Issue by TariqAHassan** [polyaxon/polyaxon#602]
### Describe the bug

Logs failing to appear in UI (and are ephemeral in CLI)

### To Reproduce

Due to [this](https://docs.polyaxon.com/faq/i-cannot-fetch-logs/) FAQ, I set up log persistence to a bucket on GCS by following [this](https://github.com/polyaxon/polyaxon/blob/master/docs/integrations/logs-on-gcs.md) guide.

I was unsure what is meant by "Google cloud storage provide an easy way to download access key as json file. You should create a secret based on that json file", but took it to mean creating a service account. I did this, granting ADMIN for GCS, downloaded the key as JSON and used `kubectl` to add the secret with the recommended command:

```
kubectl create secret generic gcs-secret --from-file=gcs-secret.json=path/to/gcs-key.json -n polyaxon
```

The `persistence` section of the `.yaml` file looks like this:

```
persistence:
  data:
    gcs-data:
      store: gcs
      bucket: gs://BUCKET-NAME-data
      secret: gcs-secret
      secretKey: gcs-secret.json
      readOnly: true
  outputs:
    outputs:
      store: gcs
      bucket: gs://BUCKET-NAME-outputs
      secret: gcs-secret
      secretKey: gcs-secret.json
  logs:
    store: gcs
    bucket: gs://BUCKET-NAME-logs
    secret: gcs-secret
    secretKey: gcs-secret.json
```

Yet, the `logs` bucket remains empty and `Failed to fetch logs` appears in the UI under logs for all experiments.

### Expected behavior

Logs to appear in the CLI and UI

### Environment

Polyaxon: `v0.5.6`.
Helm: `v2.15.2`.
