### ISSUE TITLE
Insufficient CPU and GPU error on GKE

### ISSUE THREAD

**Issue by mdsingh2013** [polyaxon/polyaxon#605]
### Describe the bug
When I try to schedule a notebook or job with resource requirements more than 1 for GPU or CPU, the deployment fails with insufficient CPU or GPU errors, when in fact I can see I have 4 GPUs, and 15 CPU nodes available with low resource usage and available

### To Reproduce

This is the corresponding config file(note: this works fine with 1 GPU request, and 1 CPU request, but when I try to go up on either it fails):

```
version: 1
kind: notebook
build:
  image: 'tensorflow/tensorflow:2.0.0-gpu-py3-jupyter'
  build_steps:
    - pip3 install -r requirements.txt
environment:
  resources:
    gpu:
      requests: 2
      limits: 2
    cpu:
      requests: 1
      limits: 1
```

Error:
unschedulable: 0/11 nodes are available: 1 Insufficient cpu, 11 Insufficient nvidia.com/gpu

### Expected behavior
Deploy a notebook/job/experiment with requested resources

### Environment
1.13.11-gke.9

```
mdsingh$ polyaxon version

Current cli version: 0.5.6.


Supported cli versions:

--------------  -----
latest_version  0.5.6
min_version     0.5.0
--------------  -----
```
