### ISSUE TITLE
nodeSelectors not working

### ISSUE THREAD

**Issue by axelperschmann** [polyaxon/polyaxon#625]
### Describe the bug
`polyaxon-config.yml` does not accept `nodeSelectors` to be defined per group (core, experiments, ...).

### To Reproduce

polyaxon-config.yml
```
nodeSelectors:
  core:
    agentpool: core
  experiments:
    agentpool: gpu
  jobs:
    agentpool: cpu
  builds:
    agentpool: cpu
  tensorboards:
    agentpool: cpu
  notebooks:
    agentpool: gpu
```

Upgrade of Polyaxon Deployment fails 
```
$ helm upgrade polyaxon polyaxon/polyaxon --namespace=polyaxon -f manifests/polyaxon-config.yml
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.tolerations): invalid type for io.k8s.api.core.v1.PodSpec.tolerations: got "map", expected "array"
```

The following configuration is accepted, but it still happens that `build`-pods are started on the GPU nodes:
```
nodeSelector:
  agentpool: cpu

postgresql:
  nodeSelector:
    agentpool: core
```

### Expected behavior
- The polyaxon-core pods should always run on the node group labeled with `agentpool: core`.
- Builds/Tensorboards/Jobs should run on `agentpool: cpu` nodes
- Notebooks/Experiments should run on `agentpool: gpu` nodes

### Environment
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
