### ISSUE TITLE
PostgresDB is not persisted between cluster restarts

### ISSUE THREAD

**Issue by jrozansk** [polyaxon/polyaxon#63]
Excerpt from polyaxon-postgres deployment:
```
...
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: data
          subPath: postgresql-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
...
```

Although I used persistent volumes in polyaxon configuration, database is not held on them. As I see in above deployment there is just directory on node mounted for postgres.
After resizing my GKE cluster to 0 and back to positive value I have database related errors. Now I even can't purge my polyaxon deployment because **polyaxon-clean-experiments** fails with following error:

```
django.db.utils.ProgrammingError: relation "experiments_experiment" does not exist
LINE 1: ...etric_id", "experiments_experiment"."commit" FROM "experimen...
```

**Comment by mouradmourafiq** [comment]
Hi @jrozansk, did you enable persistence for Postgres in your `config.yml`, i.e.

```yaml
postgres:
  persistence:
    enabled: true
```

As for the second error, yes that's due to a changed structure, and a bad handling from my side, I was thinking that I would provide migration path starting from version `0.1.0`

Sorry for the bad experience :(
