### ISSUE TITLE
Non-python related docker image and build steps confliction

### ISSUE THREAD

**Issue by Cwatana** [polyaxon/polyaxon#634]
Hello all, 

Level: Complete Beginner 

I am trying to get GATE (Geant4 Application for Tomographic Emission) running on a cluster that is managed with Polyaxon. What I've found is that building the docker image from GATE creates problems when installing with pip in the build_steps section of the .yaml file. Here, the file: 

```
version: 1

kind: experiment

framework: Gate

tags: [examples]

build:
  image: opengatecollaboration/gate:latest
  build_steps:
    - pip install polyaxon-client==0.5.6

environment:
  resources:
      cpu:
      requests: 3
      limits: 8
    memory:
      requests: 1024
      limits: 4098
    gpu:
      requests: 1
      limits: 1
            
declarations: 

run:
  cmd: python run.py
```
Building gives the following error : 
``` 
ERROR: The command '/bin/sh -c pip install polyaxon-client==0.5.6' returned a non-zero code: 127
```
I've noticed that when I build a pytorch docker image, there is no error, so I assume the problem is here...

Ultimately, I'd like to be able to run GATE simulations from a python script, and use the polyaxon_client.tracking functions to determine where my outputs from the simulations are stored. However, I can't get pip to install the packages I need to do this. Has anyone else run into a problem like this ? Suggestions / Comments are welcome! 

My work-around for this problem would ultimately be to manually change the storage location within the GATE simulation code, but I'd like to see if I can understand the underlying issues here first. 

Thank you in advance for your assistance!
