### ISSUE TITLE
env_vars aren't accessable during run

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#643]
### Feature motivation

Abitlity to access environment variables provided by build in cmd.

### Feature description
Running experiment with a yml like this doesn't work
```
---
version: 1

kind: experiment

framework: horovod

environment:
  resources:
    gpu:
      requests: 1
      limits: 1

build:
  dockerfile: Dockerfile
  env_vars:
    - ['MY_ENV_VAR_KEY1', 'MY_ENV_VAR_VALUE1']

run:
  cmd: echo test $MY_ENV_VAR_KEY1
```
Output:
```test ```

### Feature implementation

Perhaps appending an ENV to the dockerfile passed in.

**Comment by Mofef** [comment]
I found that defined env_vars are accessible in the build step (not the run step). Maybe it's intended like that

**Comment by hollowgalaxy** [comment]
I see.  I was expecting for them to be available in the run as well.

**Comment by hollowgalaxy** [comment]
@Mofef, so you were succeeded in running  my example? [Here](https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/horovod/tensorflow/Dockerfile) is the Dockerfile

**Comment by Mofef** [comment]
oh. no, sorry I didn't use your test case i just defined a experiment with a single build step and a single run step. each printing the environemnt variable. the print appeared in the log of both the experiemnt and the build

**Comment by hollowgalaxy** [comment]
I think when specifying a Dockerfile path, the environment variables are not being passed into the run environment.

**Comment by hollowgalaxy** [comment]
I have been able to add them via input params like so...
```
---
version: 1

kind: experiment

framework: horovod

input:
     - {name: my_env_var_key1, type: str, is_optional: true, default: MY_ENV_VAR_VALUE1}
environment:
  resources:
    gpu:
      requests: 1
      limits: 1

build:
  dockerfile: Dockerfile

run:
  cmd:
      - MY_ENV_VAR_KEY1 {{ my_env_var_key1 }}
      - echo test $MY_ENV_VAR_KEY1
```

However this is a ductape solution for those in same boat as me. Ideally the env_vars part should work if Dockerfile is provided.

**Comment by mouradmourafiq** [comment]
This is something that will not be in implemented in v0.x, v1 will expose all container options for advance users.

**Comment by hollowgalaxy** [comment]
But the non dockerfile build command already supports this feature. Is that because they are creating the env variables in the build context and it's being propogated to run context?

**Comment by mouradmourafiq** [comment]
I think those envs sections are confusing, if you define a dockerfile locally and have the `ENV` section in it, it won;t update your whole environment, that just a instruction for docker to build the image with those envs.

the right approach is what you did with the input, although not probably the intended behavior if you only want to reuse some constant without exposing a parameter.

this is basically wrong:

```
run:
  cmd: echo test $MY_ENV_VAR_KEY1
```

The user is requesting a value that the polyaxonfile compiler has no knowledge of, this value is not resolved at any point in time by the polyaxonfile specification.

I understand the need for some kind of templating to pass variables, and that's exactly what you did with the input. May be the input is not the right apporoach for decalaring global context constants and should be only used for I/O, in that case may be adding a global section with `constants` to defined reusable values is the way to go. WDYT?

**Comment by hollowgalaxy** [comment]
I'd start with the current env_vars section seems misleading because it seems like it would be for both build context and run context. (This may be due to not having a run context specific section).

I think perhaps there is env_vars in the run section as well. 
```
---
version: 1

kind: experiment

framework: horovod

environment:
  resources:
    gpu:
      requests: 1
      limits: 1

build:
  dockerfile: Dockerfile

run:
  env_vars:
    - ['MY_ENV_VAR_KEY1', 'MY_ENV_VAR_VALUE1']
  cmd: echo test $MY_ENV_VAR_KEY1
```
This may lead to v1 idea, which is to have more parameters added
> This is something that will not be in implemented in v0.x, v1 will expose all container options for advance users.

so that eventually, docker command would be part of the run section.
