### ISSUE TITLE
cannot specify preferredDuringSchedulingIgnoreDuringExecution term in nodeAffinity

### ISSUE THREAD

**Issue by yh-xu** [polyaxon/polyaxon#676]
### Describe the bug
I want to specify nodeAffinity in experiment to control which nodes can pods be scheduled on. I'm using polyaxonfile.yml like below:
```
...
kind: experiment
framework: pytorch
build:
 ....
environment:
  affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoreDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: kubernetes.io/hostname
                       operator: In
                       values:
                         - 'hostname' 
  resources:
   .....
...
```
Then I got errors when creating the experiment:
![image](https://user-images.githubusercontent.com/59196087/74213944-62a64e80-4cd6-11ea-9d7e-11bc8ec66530.png)

If I use "requiredDuringSchedulingIgnoreDuringExecution" instead of "preferred...." term with all other configuration unchanged, I can get experiment run successfully.

### Environment
ubuntu 16.04, polyaxon-0.6.0

**Comment by mouradmourafiq** [comment]
Sorry I did not pay attention to the root cause of this error, I reformatted the code ad it was a bit more clear, but it seems that `preferredDuringSchedulingIgnoreDuringExecution` expects a list and not a dict, the exception error actually shows that: `expect [ found {`

This is for instance how to use preemptible in GKE :
```yaml
...
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: Exists
        weight: 100
...
```
