### ISSUE TITLE
hyperband - iterations after the first run with only one resource allocated

### ISSUE THREAD

**Issue by OodapowUiPath** [polyaxon/polyaxon#705]
### Describe the bug

The second iteration schedules the new experiments in a bad state. The best example is this `Config` file obtained from the platform UI

In the test i use `epochs` as a resource.

```
version: 1
kind: experiment
framework: pytorch
build:
  image: 'pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime'
  build_steps:
    - 'pip install --no-cache-dir -U polyaxon-client[gcs]==0.6.1'
    - pip install tensorboard
environment:
  resources:
    cpu:
      limits: 2
      requests: 2
    gpu:
      limits: 1
      requests: 1
params:
  epochs: 2
  batch_size: 1000
  learning_rate: 10
run:
  cmd: >-
    python model.py \ --epochs=1 --lr=10.0 \ --batch-size=1000 \
    --test-batch-size=1000
```

It can be noticed that in the `params` key the `epochs` key has the value of 2, but in the `cmd` it has the value of 1

### To Reproduce

A link to the code used to launch the test is [HERE](https://github.com/Oodapow/polyaxon_example/blob/master/polyaxon/hptune_hb.yml)

### Expected behavior

The experiment to start with the correct number of resources in the generated command line.

### Environment

Environment:
 * kubectl
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
 * helm
```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
 *  polyaxon version
```
Current cli version: 0.6.1.

Supported cli versions:

--------------  -----
latest_version  0.6.1
min_version     0.5.0
--------------  -----
```
