### ISSUE TITLE
Add support for relative paths in `pathRef`

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#737]
### Feature motivation

In order for `pathRef` feature to be more usable and sharable, it should support relative paths.

### Feature description

Assuming we have a component in file `polyaxonfile.yml` that runs by default with CPU, this behavior should be allowed to patch the previous file with GPU:

```yaml
---
version: 1.05
kind: operation
runPatch:
  container:
    resources:
      limits:
        nvidia.com/gpu: 1
pathRef: ./polyaxonfile.yml
```

Currently the `pathRef` won't be able to resolve the file because it accepts only absolute fields. This current behaviour will make this override file useless outside of the author's environment.

### Feature implementation

The context should be passed down to the cli/client resolver method to handle relative paths similar to what it does now with absolute paths.
