### ISSUE TITLE
Polyaxonfile is not valid with environment.annotations on version 0.6.1

### ISSUE THREAD

**Issue by kylegao91** [polyaxon/polyaxon#751]
### Describe the bug

I got the following error when running `polyaxon run --upload`
```
Polyaxonfile is not valid.
Error message `__init__() got an unexpected keyword argument 'annotations'`.
```

### To Reproduce

Used the following polyaxonfile with version 0.6.1

```
version: 1
kind: experiment
build:
  image: alpine
environment:
  annotations:
    anno1: value1
run:
  cmd:
  - echo "Hello world!"
```

### Expected behavior
Able to add annotations to the pod that executes the experiment.

### Environment
EKS k8s cluster.
