### ISSUE TITLE
0.6.1 component not support

### ISSUE THREAD

**Issue by TPL-egg-HIT** [polyaxon/polyaxon#824]
### Environment
I have two virtual machine: one master and one worker,
OS: centos 7
K8S version: 1.18.2
docker version: 18.06.3-ce

#### 1. install polyaxon
command ：`helm install polyaxon polyaxon/polyaxon --namespace=polyaxon -f polyaxon-config.yml`
here is my polyaxonconfig.yml file
```
namespace: polyaxon
rbac:
  enabled: false
ingress:
  enabled: false
serviceType: NodePort
```
in fact I tried many polyaxonconfig.yml file include [here](https://install.polyaxon.com/deploy)，but not in use。
This step is ok，and I did configs according to the hint。Finally the polyaxon pods is running。
#### 2. run mnist
command as follow：
```
git clone https://github.com/polyaxon/polyaxon-examples.git
cd polyaxon-examples/in_cluster/tensorflow/mnist/
polyaxon login --username=root --password=rootpassword
polyaxon project create --name=cifar10 --description='Train and evaluate a CIFAR-10 ResNet model on polyaxon'
polyaxon init cifar10
polyaxon upload
polyaxon run -f polyaxonfile.yml
```
at first I used the original file ,but `component` is not supported, here is the log
```
Polyaxonfile is not valid.
Error message `The Polyaxonfile with kind `component` is not a supported value.`.
```
so I checked others'log, and I changed the polyaxonfile.yml as follow:
```
version: 1
kind: experiment
tags: [examples, tensorflow]

environment:
  node_selector: 
    kubernetes.io/hostname: worker01 
  resources: 
    cpu: 
      requests: 1 
      limits: 1 

build:
  image: polyaxon/polyaxon-examples
  build_steps:
    - pip3 install polyaxon-client 
run: 
  cmd: python model.py
```
Finally this experiment is created, but only created. The dashboard has no log, and `polyaxon experiment -xp 1 logs` only has `created ...`

### Question
1. Polyaxon 0.6.1 do support `component`, if so what should I do to support `component`?
2. Whether `experiment` is supported or not?
3. Where I can see the mnist training logs?
By the way, the docs are not matched with the code, and I am in mess.....
Thanks!!!
