### ISSUE TITLE
NGINX Ingress - slow download speed

### ISSUE THREAD

**Issue by Oodapow** [polyaxon/polyaxon#826]
### Describe the bug
Setting up the platform with ingress enabled, NGINX as the ingress controller and TLS enabled will reduce the download speed of artefacts (~150KB/s).

### To Reproduce
Changes to the polyaxon file.
```
ingress:
  enabled: true
  hostName: <NAME>
  tls:
  - secretName: <SECRET>
    hosts:
      - <NAME>
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
```

The nginx config got updated inside the ingress controller pod; the annotations seem to work just fine.

### Expected behavior

Download faster than ~150KB/s

### Environment
Kubernetes: 1.15.11
Helm: 2.15.1
Polyaxon: 0.6.1 Community Edition
