### ISSUE TITLE
Investigate core resolver does not inject templates into context

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#827]
### Describe the bug

the following snippet will be resolved correctly in EE and not in CE.

```yaml
- name: ports
  isOptional: true
  isList: true
  type: int
  value: [8091]
run:
  kind: service
  ports: "{{ports}}"
```

### Expected behavior

All templated variables should be resolved and injected into the context correctly.

This is likely related to #802

### Environment

CE 1.0.99
