### ISSUE TITLE
Integration with ingress: dns resolve error

### ISSUE THREAD

**Issue by chenglin** [polyaxon/polyaxon#843]
### Describe the bug
I enabled ingress when depoly polyaxon.
When I run an experiment from `https://github.com/polyaxon/polyaxon-quick-start`,  there are errors about `Temporary failure in name resolution`

### To Reproduce

1. deploy polyaxon: 
```
polyaxon admin deploy -f polyaxon_config.yaml
```
 polyaxon_config.yaml:
```
deploymentType: microk8s
deploymentChart: platform
deploymentVersion: 1.0.99-rc2

gateway:
  imageTag: 1.0.99-rc2

streams:
  imageTag: 1.0.99-rc2

api:
  imageTag: 1.0.99-rc2

scheduler:
  imageTag: 1.0.99-rc2

hooks:
  imageTag: 1.0.99-rc2

init:
  imageTag: 1.0.99-rc2

sidecar:
  imageTag: 1.0.99-rc2


ingress:
  enabled: true
  hostName: polyaxon.domainname.com

user:
  username: root
  email: root@polyaxon.local
  password: rootpassword
```
2. clone polyaxon-quick-start:
```
git clone https://github.com/polyaxon/polyaxon-quick-start
```
3. create a project named quick-start from the web ui
4. run a experiment
```
cd polyaxon-quick-start
polyaxon run -p quick-start -f experimentation/simple.yml
```
5. open web ui log tab
![image](https://user-images.githubusercontent.com/1031972/85017698-8276e300-b19e-11ea-9a08-e4f67a531d7a.png)

6. polyaxon-init-git-polyaxon-quick-start
```
polyaxon-init-git-polyaxon-quick-start:
    Container ID:  containerd://70e5a7c9b6b74a90519f2b9f481224c9a7241c891fa59103a9c9bffad4e45260
    Image:         polyaxon/polyaxon-init:1.0.99-rc2
    Image ID:      docker.io/polyaxon/polyaxon-init@sha256:ab195eda86530e696379f0b78b3b7a674f348c5fcc6cb8e072cccebe3529b6a8
    Port:          <none>
    Host Port:     <none>
    Command:
      polyaxon
      initializer
      git
    Args:
      --repo_path=/plx-context/artifacts/polyaxon-quick-start
      --url=https://github.com/polyaxon/polyaxon-quick-start
    State:          Running
      Started:      Thu, 18 Jun 2020 19:41:46 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2000Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      POLYAXON_API_HOST:                                polyaxon.domainname.com
      POLYAXON_IS_MANAGED:                              true
      POLYAXON_API_VERSION:                             v1
      POLYAXON_K8S_NODE_NAME:                            (v1:spec.nodeName)
      POLYAXON_K8S_NAMESPACE:                           polyaxon (v1:metadata.namespace)
      POLYAXON_K8S_POD_ID:                              plx-operation-cc2e0a4ef46941d586610e1a01cb5833-jdb92 (v1:metadata.name)
      POLYAXON_RUN_INSTANCE:                             (v1:metadata.labels['app.kubernetes.io/instance'])
      POLYAXON_HEADER:                                  X-POLYAXON-SERVICE
      POLYAXON_HEADER_SERVICE:                          initializer
      POLYAXON_AUTHENTICATION_TYPE:                     Token
      POLYAXON_CONNECTION_SCHEMA_POLYAXON-QUICK-START:  {"name": "polyaxon-quick-start", "kind": "git", "schema": {"url": "https://github.com/polyaxon/polyaxon-quick-start", "kind": "git"}}
    Mounts:
      /plx-context/artifacts from artifacts-context (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from polyaxon-polyaxon-runs-sa-token-8f7mk (ro)
```

### Expected behavior
experiment finished successfully

### Environment
OS: ubuntu 20.04
k8s: microk8s, one node
