### ISSUE TITLE
Artifacts initializer does not default to the artifacts store connection

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#846]
### Describe the bug

Artifacts initializer is not using the default artifactsStore when no connection is provided.

### To Reproduce

This init section will be ignored, but it should use the default artifactsStore connection:

```yaml
init:
    -  artifacts: {"dirs": ["path"]}
```

Providing a connection will initialize the path

```yaml
init:
    - connection: 'gs'
      artifacts: {"dirs": ["path"]}
```

### Expected behavior

It should work as expected and use the default connection.

### Environment

I believe a regression in the new v1.0.99-rc3
