### ISSUE TITLE
cant deploy with `artifactsStore` config

### ISSUE THREAD

**Issue by tricktreat** [polyaxon/polyaxon#871]
### Unclear documentation

Version:
```
polyaxon: v1.1.0
helm: v3.2.4
kubernetes: v1.18.4
```

Follow https://polyaxon.com/integrations/artifacts-on-pvc/

my `pvc-nfs-artifacts.yml`
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-artifacts
spec:
  capacity:
    storage: 45Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.15.82.46  # Use the right IP
    path: "/data/plx-artifacts"
  claimRef:
    namespace: polyaxon
    name: polyaxon-pvc-artifacts
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 45Gi
```

my `polyaxon-config.yml`
```yml
artifactsStore:
  name: polyaxon-artifacts
  kind: volume_claim
  schema:
    mountPath: /plx-data
    volumeClaim: polyaxon-pvc-artifacts
```
when i run:
```bash
polyaxon admin deploy -f polyaxon-config.yml --check

```
got:
```
Polyaxon deployment file is not valid 
Error message `{'artifactsStore': ['Unknown field.']}`.
```

and **can you afford a complete polyaxon default setup config?** I alse got `Unknown field` when using `email.enabled` and `gateway` in setup config.
