### ISSUE TITLE
No logs available in UI

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#873]
### Describe the bug
When starting an experiment I expect logs to be viewable in the UI, however no logs are found. I can fetch the logs with `kubectl logs -f -n polyaxon <pod>`.
The artifactsStore seems to be properly setup, as I can see Tensorboard logfiles on the storage.

Polyaxon-polyaxon-api pod continuosly logs:
`WARNING 2020-07-01 14:14:37,854 log 118 140479180982016 Not Found: /streams/v1/polyaxon/default/***/runs/159e974cae784650b08f6275514c4940/logs
[pid: 118|app: 0|req: 466/1865] 10.42.7.32 () {62 vars in 1234 bytes} [Wed Jul  1 14:14:37 2020] GET /streams/v1/polyaxon/default/***/runs/159e974cae784650b08f6275514c4940/logs?force=true => generated 1221 bytes in 5 msecs (HTTP/1.1 404) 5 headers in 158 bytes (1 switches on core 0)`

### To Reproduce
polyaxonfile.yml
```
version: 1.1
version: 1.1
kind: component
name: simple-experiment
description: Minimum information to run this TF.Keras example
tags: [examples]
run:
  kind: job
  init:
  - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
  container:
    image: polyaxon/polyaxon-quick-start
    workingDir: "{{ globals.artifacts_path }}/polyaxon-quick-start"
    command: [python3, model.py]
```

### Expected behavior
Logs viewable in UI or with `polyaxon ops logs`

### Environment
pip freeze | grep polyaxon
polyaxon==1.1.0
polyaxon-sdk==1.1.0

```
deploymentChart: platform
deploymentVersion: 1.1.0

artifactsStore:
  name: minio
  kind: s3
  schema: {"bucket": "***"}
  secret:
    name: "***"

connections:
  - name: data
    kind: volume_claim
    schema:
      mountPath: ***
      volumeClaim: ***
      readOnly: true

scheduler:
  enabled: true

streams:
  enabled: true

postgresql:
  persistence:
    enabled: true
    storageClass: nfs

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: nfs
  slave:
    persistence:
      enabled: true
      storageClass: nfs
broker: redis

rabbitmq-ha:
  enabled: false

adminViewEnabled: true
```

**Comment by mouradmourafiq** [comment]
Can you use:

 * use the `-u` flag:

```yaml
  container:
    command: [python3, '-u', model.py]
```

 * use an env var `PYTHONUNBUFFERED`

```yaml
  container:
    command: [python3, model.py]
    env:
      - name: PYTHONUNBUFFERED
        value: "true"
```
