### ISSUE TITLE
how to use hostPID in yml

### ISSUE THREAD

**Issue by zhaohb** [polyaxon/polyaxon#936]
Now, I am using 1.1.3 polyaxon, Polyaxon is deployed based on k8s. and I want add hostPID :true in one component，as follow:

```yaml
version: 1.1
kind: component
name: test
run:
  kind: job
  container:
    name: aaaa
    image: test:v2
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_RAWIO"]
    volumeMounts:
    - name: bsp
      mountPath: /mnt/
  volumes:
    name: bsp
    hostPath:
      path: /mnt
```

How should I add hostPID in this yaml file? 
thank you

**Comment by mouradmourafiq** [comment]
Hi @zhaohb I formatted you code snippet.

I am not sure why we decided on the list in the [environment section](https://github.com/polyaxon/polyaxon/blob/master/sdks/protos/v1/polyflow/environment.proto#L24), the host pid does not appear to be in the list.

I will update this issue by today or tomorrow to let you know if we will add that field.

If the change makes sense it will be part of v1.1.5 coming on Monday.

**Comment by zhaohb** [comment]
thank you @mouradmourafiq , The reason why I use hostpid is that I want to use Heterogeneous devices in polyaxon. Now there is a problem with Heterogeneous device environment, that is, the PID namespace must be shared with the host， so I want use hostPID, I hope to add that field.

thanks

**Comment by mouradmourafiq** [comment]
Thanks for the quick feedback, since we already allow `hostNetwork` and `hostAliases`, we can add the `hostPID`. Clusters that don't want to allow these fields alter this behavior with PSPs and SAs.

It will be part of v1.1.5, and can be used as the following:
```yaml
version: 1.1
kind: component
name: test
run:
  kind: job
  environment:
    hostPID: true
  container:
    name: aaaa
    image: test:v2
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_RAWIO"]
    volumeMounts:
    - name: bsp
      mountPath: /mnt/
  volumes:
    name: bsp
    hostPath:
      path: /mnt
```
