### ISSUE TITLE
tfjob can not work

### ISSUE THREAD

**Issue by zhaohb** [polyaxon/polyaxon#995]
###  I want to use tfjob to run tensorflow distributed example, but experiments status is queued, why?

```yaml
version: 1.1
kind: component
name: cpu-tf
run:
  kind: tfjob
  worker:
    replicas: 1
    container:
      name: cpu-tf
      image: ngnix:1.14.2
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_RAWIO"]
```

### result:
```bash
[root@master hostdev_gpu]# polyaxon ops ls

Experiments for project `default/cifar10`.


Navigation:

-----  -
count  4
-----  -

Runs:

UUID                              NAME    TAGS                                    USER    CREATED_AT         UPDATED_AT         STARTED_AT      FINISHED_AT    RUN_TIME    IS_MANAGED    STATUS    BOOKMARKED    KIND    META_KIND    HUB
--------------------------------  ------  --------------------------------------  ------  -----------------  -----------------  --------------  -------------  ----------  ------------  --------  ------------  ------  -----------  -----
b110c41ba70a4429be884c9386ab0a92  cpu-tf                                                  a few seconds ago  a few seconds ago                                             True          queued                  job
59b50962f93c421fa263a38f4b1a97fc          ['examples', 'tensorflow', 'kubeflow']          7 minutes ago      7 minutes ago                                                 True          queued                  job
0fd6765f2d924747a117d4f59f35ffe6  gpu-tf                                                  13 minutes ago     13 minutes ago     13 minutes ago                             True          running                 job
5e76977323ef46229c756669117e4c2a  gpu-tf                                                  21 minutes ago     21 minutes ago                                                True          queued                  job

```

 what should i do for this issue?

I am useing  polyaxon v1.1.5

**Comment by mouradmourafiq** [comment]
The example you shared gets scheduled, but it does not run because the image is wrong. I think that you did not deploy the [TFOperator](https://polyaxon.com/integrations/tfjob/#deploy-the-tensorflowjob-operator), please make sure you have the TFOperator running in your k8s cluster. You can deploy the operator on your own or use the [charts](https://polyaxon.com/integrations/kubeflow/#deploying-kubeflow-operators) provided by Polyaxon.

**Comment by zhaohb** [comment]
Thank you for your reply. I have changed the yaml file and installed tfjob in the way you said. 
```yaml
version: 1.1
kind: component
name: cpu-tf
run:
  kind: tfjob
  worker:
    replicas: 1
    container:
      name: cpu-tf
      image: nginx:1.14.2
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_RAWIO"]
```
and install tfjob:
```bash
helm install polyaxon/tfjob --namespace=polyaxon
```
Now tfjob can be used normally. In addition, do you have an example of tensorflow using tfjob distributed training? Can you share it, including yaml files.

thank you very much!
