### ISSUE TITLE
Add docs about the basics of using containers

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#996]
### Missing Documentation

Several users ask questions about how to organize their commands. In v0 there was a single `cmd` where users provide a list of commands and Polyaxon would join them with `&`.

The current documentation just links to the Kubernetes reference for containers. Several users do not know Kubernetes and should not learn about it unless they want to use advanced features.

We need to provide a guide on how to use the usual aspects of the container section:

 * Command and args:

```yaml
command: ["/bin/sh","-c"]
args: ["command one; command two && command three"]
```

 * Injecting resources:

```yaml
resources:
    limits:
      cpu: 500m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 50Mi
```

 * Using the workingDir to avoid prepending commands with the artifacts path:

```yaml
workingDir: "{{ context or globals.artifacts_path }}"
```
